/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Advanced_Pixel LCD7_16.c                              *
* Font:        Advanced Pixel LCD-7                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x77 (119)                                    *
* Character enabled:   0x76 (118)                                    *
* Character enabled:   0x43 (67)                                     *
* Character enabled:   0x46 (70)                                     *
* Edit/Insert/Right     at character 0x43 (67)                       *
* Edit/Delete/Right     at character 0x43 (67)                       *
* Edit/Insert/Left      at character 0x43 (67)                       *
* Edit/Insert/Left      at character 0x43 (67)                       *
* Edit/Insert/Left      at character 0x43 (67)                       *
* Edit/Insert/Left      at character 0x43 (67)                       *
* Edit/Insert/Left      at character 0x46 (70)                       *
* Edit/Insert/Left      at character 0x46 (70)                       *
* Edit/Insert/Left      at character 0x46 (70)                       *
* Edit/Insert/Left      at character 0x46 (70)                       *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontAdvanced_PixelLCD7_16;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_002E[  2] = { /* code 002E, FULL STOP */
  0x74,
  0x74
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0030[ 45] = { /* code 0030, DIGIT ZERO */
  0x7F, 0x7F, 0x80,
  0xDF, 0x7E, 0x90,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0x70, 0x01, 0x80,
  0xC0, 0x00, 0x50,
  0x70, 0x01, 0x80,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xDF, 0x7E, 0x90,
  0x7F, 0x7F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0031[ 30] = { /* code 0031, DIGIT ONE */
  0xFE, 0x00,
  0xFA, 0x40,
  0x07, 0x40,
  0x07, 0x40,
  0x07, 0x40,
  0x07, 0x40,
  0x06, 0x00,
  0x01, 0x40,
  0x06, 0x00,
  0x07, 0x40,
  0x07, 0x40,
  0x07, 0x40,
  0x07, 0x40,
  0x02, 0x40,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0032[ 45] = { /* code 0032, DIGIT TWO */
  0x3F, 0x7F, 0x80,
  0x0F, 0x7E, 0x90,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x01, 0x55, 0x80,
  0x0F, 0xFD, 0x00,
  0x31, 0x54, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xDF, 0x7E, 0x00,
  0x7F, 0x7F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0033[ 45] = { /* code 0033, DIGIT THREE */
  0x3F, 0x7F, 0x80,
  0x0F, 0x7E, 0x90,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x01, 0x55, 0x80,
  0x0F, 0xFD, 0x50,
  0x01, 0x55, 0x80,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x0F, 0x7E, 0x90,
  0x3F, 0x7F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0034[ 45] = { /* code 0034, DIGIT FOUR */
  0x00, 0x00, 0x00,
  0xC0, 0x00, 0x90,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0x31, 0x55, 0x80,
  0x0F, 0xFD, 0x50,
  0x01, 0x55, 0x80,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x00, 0x90,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0035[ 45] = { /* code 0035, DIGIT FIVE */
  0x7F, 0x7F, 0x80,
  0xDF, 0x7E, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0x31, 0x54, 0x00,
  0x0F, 0xFD, 0x00,
  0x01, 0x55, 0x80,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x0F, 0x7E, 0x90,
  0x3F, 0x7F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0036[ 45] = { /* code 0036, DIGIT SIX */
  0x7F, 0x7F, 0x80,
  0xDF, 0x7E, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0x71, 0x54, 0x00,
  0xCF, 0xFD, 0x00,
  0x71, 0x55, 0x80,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xDF, 0x7E, 0x90,
  0x7F, 0x7F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0037[ 45] = { /* code 0037, DIGIT SEVEN */
  0x7F, 0x7F, 0x80,
  0xDF, 0x7E, 0x90,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0x30, 0x01, 0x80,
  0x00, 0x00, 0x50,
  0x00, 0x01, 0x80,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x00, 0x90,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0038[ 45] = { /* code 0038, DIGIT EIGHT */
  0x7F, 0x7F, 0x80,
  0xDF, 0x7E, 0x90,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0x31, 0x55, 0x80,
  0x0F, 0xFD, 0x00,
  0x31, 0x55, 0x80,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xDF, 0x7E, 0x90,
  0x7F, 0x7F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0039[ 45] = { /* code 0039, DIGIT NINE */
  0x7F, 0x7F, 0x80,
  0xDF, 0x7E, 0x90,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0x31, 0x55, 0x80,
  0x0F, 0xFD, 0x50,
  0x01, 0x55, 0x80,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x00, 0x01, 0xD0,
  0x0F, 0x7E, 0x90,
  0x3F, 0x7F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0043[ 60] = { /* code 0043, LATIN CAPITAL LETTER C */
  0xFC, 0x7F, 0x7F, 0x80,
  0xCC, 0xDF, 0x7E, 0x00,
  0xFC, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0x70, 0x00, 0x00,
  0x00, 0xC0, 0x00, 0x00,
  0x00, 0x70, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xDF, 0x7E, 0x00,
  0x00, 0x7F, 0x7F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0046[ 60] = { /* code 0046, LATIN CAPITAL LETTER F */
  0xFC, 0x7F, 0x7F, 0x80,
  0xCC, 0xDF, 0x7E, 0x00,
  0xFC, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0x71, 0x54, 0x00,
  0x00, 0xCF, 0xFD, 0x00,
  0x00, 0x71, 0x54, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xF0, 0x00, 0x00,
  0x00, 0xC0, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0056[ 45] = { /* code 0076, LATIN SMALL LETTER V */
  0x00, 0x00, 0x00,
  0xC0, 0x00, 0x90,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0x70, 0x01, 0x80,
  0xC0, 0x00, 0x50,
  0x70, 0x01, 0x80,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xB0, 0x01, 0xC0,
  0x20, 0x01, 0x00,
  0x0B, 0x7C, 0x00,
  0x02, 0x70, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontAdvanced_PixelLCD7_16_0057[ 45] = { /* code 0077, LATIN SMALL LETTER W */
  0x00, 0x00, 0x00,
  0xC0, 0x00, 0x90,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0xF0, 0x01, 0xD0,
  0x70, 0x01, 0x80,
  0xC0, 0x00, 0x50,
  0x70, 0x01, 0x80,
  0xF0, 0x81, 0xD0,
  0xF0, 0xD1, 0xD0,
  0xF0, 0xD1, 0xD0,
  0xF0, 0x81, 0xD0,
  0xDF, 0x7E, 0x90,
  0x7F, 0x7F, 0x80
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontAdvanced_PixelLCD7_16_CharInfo[16] = {
   {   1,   1,   0,  16,   5, acGUI_FontAdvanced_PixelLCD7_16_0020 } /* code 0020, SPACE */
  ,{   3,   2,   0,  14,   4, acGUI_FontAdvanced_PixelLCD7_16_002E } /* code 002E, FULL STOP */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  15,   5,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0031 } /* code 0031, DIGIT ONE */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0032 } /* code 0032, DIGIT TWO */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0034 } /* code 0034, DIGIT FOUR */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0035 } /* code 0035, DIGIT FIVE */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0036 } /* code 0036, DIGIT SIX */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0037 } /* code 0037, DIGIT SEVEN */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0038 } /* code 0038, DIGIT EIGHT */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0039 } /* code 0039, DIGIT NINE */
  ,{  13,  15,   0,   1,  15, acGUI_FontAdvanced_PixelLCD7_16_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  13,  15,   0,   1,  15, acGUI_FontAdvanced_PixelLCD7_16_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0056 } /* code 0076, LATIN SMALL LETTER V */
  ,{  10,  15,   0,   1,  11, acGUI_FontAdvanced_PixelLCD7_16_0057 } /* code 0077, LATIN SMALL LETTER W */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontAdvanced_PixelLCD7_16_Prop6 = {
   0x0056 /* first character */
  ,0x0057 /* last character  */
  ,&GUI_FontAdvanced_PixelLCD7_16_CharInfo[ 14] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontAdvanced_PixelLCD7_16_Prop5 = {
   0x0046 /* first character */
  ,0x0046 /* last character  */
  ,&GUI_FontAdvanced_PixelLCD7_16_CharInfo[ 13] /* address of first character */
  ,&GUI_FontAdvanced_PixelLCD7_16_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontAdvanced_PixelLCD7_16_Prop4 = {
   0x0043 /* first character */
  ,0x0043 /* last character  */
  ,&GUI_FontAdvanced_PixelLCD7_16_CharInfo[ 12] /* address of first character */
  ,&GUI_FontAdvanced_PixelLCD7_16_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontAdvanced_PixelLCD7_16_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontAdvanced_PixelLCD7_16_CharInfo[  2] /* address of first character */
  ,&GUI_FontAdvanced_PixelLCD7_16_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontAdvanced_PixelLCD7_16_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontAdvanced_PixelLCD7_16_CharInfo[  1] /* address of first character */
  ,&GUI_FontAdvanced_PixelLCD7_16_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontAdvanced_PixelLCD7_16_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontAdvanced_PixelLCD7_16_CharInfo[  0] /* address of first character */
  ,&GUI_FontAdvanced_PixelLCD7_16_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontAdvanced_PixelLCD7_16 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontAdvanced_PixelLCD7_16_Prop1}
  ,14 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

