/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Custom_Font_15.c                                      *
* Font:        Advanced Pixel LCD-7                                  *
* Height:      15                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character disabled:  0x3A (58)                                     *
* Character disabled:  0x3B (59)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
* Character enabled:   0x2E (46)                                     *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Delete/Bottom    at character 0x30 (48)                       *
* Edit/Delete/Bottom    at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Insert/Top       at character 0x30 (48)                       *
* Edit/Delete/Bottom    at character 0x30 (48)                       *
* Edit/Insert/Bottom    at character 0x30 (48)                       *
* Edit/Delete/Top       at character 0x30 (48)                       *
* Edit/Decrease/Top     of font.                                     *
* Edit/Cursor Distance/Increase at character 0x30 (48)               *
* Edit/Cursor Distance/Decrease at character 0x30 (48)               *
* Edit/Cursor Distance/Decrease at character 0x30 (48)               *
* Edit/Delete/Right     at character 0x30 (48)                       *
* Edit/Delete/Right     at character 0x30 (48)                       *
* Edit/Cursor Distance/Increase at character 0x30 (48)               *
* Edit/Cursor Distance/Increase at character 0x30 (48)               *
* Pixel index of character 0x30 (48) at 0/0 set to 1                 *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Delete/Right     at character 0x31 (49)                       *
* Edit/Delete/Right     at character 0x31 (49)                       *
* Edit/Delete/Right     at character 0x31 (49)                       *
* Edit/Delete/Right     at character 0x31 (49)                       *
* Edit/Delete/Right     at character 0x31 (49)                       *
* Edit/Insert/Right     at character 0x31 (49)                       *
* Edit/Insert/Right     at character 0x31 (49)                       *
* Edit/Insert/Right     at character 0x31 (49)                       *
* Edit/Insert/Right     at character 0x31 (49)                       *
* Edit/Insert/Left      at character 0x31 (49)                       *
* Edit/Delete/Right     at character 0x31 (49)                       *
* Edit/Delete/Left      at character 0x31 (49)                       *
* Edit/Delete/Right     at character 0x31 (49)                       *
* Edit/Delete/Right     at character 0x31 (49)                       *
* Edit/Cursor Distance/Increase at character 0x31 (49)               *
* Edit/Cursor Distance/Increase at character 0x31 (49)               *
* Edit/Cursor Distance/Increase at character 0x31 (49)               *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Delete/Right     at character 0x32 (50)                       *
* Edit/Insert/Right     at character 0x32 (50)                       *
* Edit/Insert/Right     at character 0x32 (50)                       *
* Edit/Insert/Right     at character 0x32 (50)                       *
* Edit/Insert/Right     at character 0x32 (50)                       *
* Edit/Insert/Right     at character 0x32 (50)                       *
* Edit/Insert/Right     at character 0x32 (50)                       *
* Edit/Insert/Right     at character 0x32 (50)                       *
* Edit/Insert/Right     at character 0x32 (50)                       *
* Edit/Cursor Distance/Increase at character 0x32 (50)               *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Delete/Right     at character 0x33 (51)                       *
* Edit/Insert/Right     at character 0x33 (51)                       *
* Edit/Insert/Right     at character 0x33 (51)                       *
* Edit/Insert/Right     at character 0x33 (51)                       *
* Edit/Insert/Right     at character 0x33 (51)                       *
* Edit/Insert/Right     at character 0x33 (51)                       *
* Edit/Insert/Right     at character 0x33 (51)                       *
* Edit/Insert/Right     at character 0x33 (51)                       *
* Edit/Cursor Distance/Increase at character 0x33 (51)               *
* Pixel index of character 0x33 (51) at 1/7 set to 0                 *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Delete/Right     at character 0x34 (52)                       *
* Edit/Insert/Right     at character 0x34 (52)                       *
* Edit/Insert/Right     at character 0x34 (52)                       *
* Edit/Insert/Right     at character 0x34 (52)                       *
* Edit/Insert/Right     at character 0x34 (52)                       *
* Edit/Insert/Right     at character 0x34 (52)                       *
* Edit/Insert/Right     at character 0x34 (52)                       *
* Edit/Insert/Right     at character 0x34 (52)                       *
* Edit/Insert/Right     at character 0x34 (52)                       *
* Edit/Cursor Distance/Increase at character 0x34 (52)               *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x35 (53)                       *
* Edit/Insert/Right     at character 0x35 (53)                       *
* Edit/Insert/Right     at character 0x35 (53)                       *
* Edit/Insert/Right     at character 0x35 (53)                       *
* Edit/Insert/Right     at character 0x35 (53)                       *
* Edit/Insert/Right     at character 0x35 (53)                       *
* Edit/Insert/Right     at character 0x35 (53)                       *
* Edit/Insert/Right     at character 0x35 (53)                       *
* Edit/Insert/Right     at character 0x35 (53)                       *
* Edit/Cursor Distance/Increase at character 0x35 (53)               *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Delete/Right     at character 0x36 (54)                       *
* Edit/Insert/Right     at character 0x36 (54)                       *
* Edit/Insert/Right     at character 0x36 (54)                       *
* Edit/Insert/Right     at character 0x36 (54)                       *
* Edit/Insert/Right     at character 0x36 (54)                       *
* Edit/Insert/Right     at character 0x36 (54)                       *
* Edit/Insert/Right     at character 0x36 (54)                       *
* Edit/Insert/Right     at character 0x36 (54)                       *
* Edit/Insert/Right     at character 0x36 (54)                       *
* Edit/Cursor Distance/Increase at character 0x36 (54)               *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Delete/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Insert/Right     at character 0x37 (55)                       *
* Edit/Cursor Distance/Increase at character 0x37 (55)               *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Delete/Right     at character 0x38 (56)                       *
* Edit/Insert/Right     at character 0x38 (56)                       *
* Edit/Insert/Right     at character 0x38 (56)                       *
* Edit/Insert/Right     at character 0x38 (56)                       *
* Edit/Insert/Right     at character 0x38 (56)                       *
* Edit/Insert/Right     at character 0x38 (56)                       *
* Edit/Insert/Right     at character 0x38 (56)                       *
* Edit/Insert/Right     at character 0x38 (56)                       *
* Edit/Insert/Right     at character 0x38 (56)                       *
* Edit/Cursor Distance/Increase at character 0x38 (56)               *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Delete/Right     at character 0x39 (57)                       *
* Edit/Insert/Right     at character 0x39 (57)                       *
* Edit/Insert/Right     at character 0x39 (57)                       *
* Edit/Insert/Right     at character 0x39 (57)                       *
* Edit/Insert/Right     at character 0x39 (57)                       *
* Edit/Insert/Right     at character 0x39 (57)                       *
* Edit/Insert/Right     at character 0x39 (57)                       *
* Edit/Insert/Right     at character 0x39 (57)                       *
* Edit/Insert/Right     at character 0x39 (57)                       *
* Edit/Cursor Distance/Increase at character 0x39 (57)               *
* Edit/Delete/Right     at character 0x2E (46)                       *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Move/Left        at character 0x2E (46)                       *
* Edit/Move/Left        at character 0x2E (46)                       *
* Edit/Move/Left        at character 0x2E (46)                       *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontCustom_Font_15;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_002E[  2] = { /* code 002E, FULL STOP */
  0xF4,
  0xF4
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0030[ 30] = { /* code 0030, DIGIT ZERO */
  0xFF, 0xFF,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xFF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0031[ 15] = { /* code 0031, DIGIT ONE */
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0032[ 30] = { /* code 0032, DIGIT TWO */
  0xFF, 0xFF,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0xFF, 0xFF,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0033[ 30] = { /* code 0033, DIGIT THREE */
  0xFF, 0xFF,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x07,
  0x00, 0x1E,
  0x00, 0x78,
  0x0F, 0xE0,
  0x00, 0x78,
  0x00, 0x1E,
  0x00, 0x07,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0xFF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0034[ 30] = { /* code 0034, DIGIT FOUR */
  0xC0, 0x0C,
  0xC0, 0x0C,
  0xC0, 0x0C,
  0xC0, 0x0C,
  0xC0, 0x0C,
  0xC0, 0x0C,
  0xC0, 0x0C,
  0xC0, 0x0C,
  0xC0, 0x0C,
  0xFF, 0xFF,
  0x00, 0x0C,
  0x00, 0x0C,
  0x00, 0x0C,
  0x00, 0x0C,
  0x00, 0x0C
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0035[ 30] = { /* code 0035, DIGIT FIVE */
  0xFF, 0xFF,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFF, 0xFF,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0xFF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0036[ 30] = { /* code 0036, DIGIT SIX */
  0xFF, 0xFF,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFF, 0xFF,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xFF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0037[ 30] = { /* code 0037, DIGIT SEVEN */
  0xFF, 0xFF,
  0x00, 0x03,
  0x00, 0x07,
  0x00, 0x0D,
  0x00, 0x1C,
  0x00, 0x34,
  0x00, 0x70,
  0x00, 0xD0,
  0x01, 0xC0,
  0x03, 0x40,
  0x07, 0x00,
  0x0D, 0x00,
  0x1C, 0x00,
  0x34, 0x00,
  0x30, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0038[ 30] = { /* code 0038, DIGIT EIGHT */
  0xFF, 0xFF,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xFF, 0xFF,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xFF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontCustom_Font_15_0039[ 30] = { /* code 0039, DIGIT NINE */
  0xFF, 0xFF,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xFF, 0xFF,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0x00, 0x03,
  0xFF, 0xFF
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontCustom_Font_15_CharInfo[12] = {
   {   1,   1,   0,  15,   5, acGUI_FontCustom_Font_15_0020 } /* code 0020, SPACE */
  ,{   2,   2,   0,  13,   4, acGUI_FontCustom_Font_15_002E } /* code 002E, FULL STOP */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0030 } /* code 0030, DIGIT ZERO */
  ,{   1,  15,   5,   0,  10, acGUI_FontCustom_Font_15_0031 } /* code 0031, DIGIT ONE */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0032 } /* code 0032, DIGIT TWO */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0033 } /* code 0033, DIGIT THREE */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0034 } /* code 0034, DIGIT FOUR */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0036 } /* code 0036, DIGIT SIX */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  15,   0,   0,  10, acGUI_FontCustom_Font_15_0039 } /* code 0039, DIGIT NINE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCustom_Font_15_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontCustom_Font_15_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCustom_Font_15_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontCustom_Font_15_CharInfo[  1] /* address of first character */
  ,&GUI_FontCustom_Font_15_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontCustom_Font_15_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontCustom_Font_15_CharInfo[  0] /* address of first character */
  ,&GUI_FontCustom_Font_15_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontCustom_Font_15 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,15 /* height of font  */
  ,15 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontCustom_Font_15_Prop1}
  ,14 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

