/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Ebrima40_B.c                                          *
* Font:        Ebrima                                                *
* Height:      40                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  40                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x4C (76)                                     *
* Character enabled:   0x75 (117)                                    *
* Character enabled:   0x78 (120)                                    *
* Character enabled:   0x65 (101)                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontEbrima40_B;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontEbrima40_B_004C[ 54] = { /* code 004C, LATIN CAPITAL LETTER L */
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0x00, 0x00,
  0xFF, 0xFF, 0xF0,
  0xFF, 0xFF, 0xF0,
  0xFF, 0xFF, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontEbrima40_B_0065[ 52] = { /* code 0065, LATIN SMALL LETTER E */
  0x00, 0xBF, 0xE0, 0x00,
  0x0B, 0xFF, 0xFD, 0x00,
  0x2F, 0xFF, 0xFF, 0x00,
  0x7F, 0xC0, 0xBF, 0x80,
  0xBF, 0x00, 0x3F, 0xC0,
  0xFF, 0xFF, 0xFF, 0xC0,
  0xFF, 0xFF, 0xFF, 0xC0,
  0xFF, 0x00, 0x00, 0x00,
  0xFF, 0x40, 0x00, 0x00,
  0x7F, 0xD0, 0x06, 0x00,
  0x3F, 0xFF, 0xFF, 0x00,
  0x0F, 0xFF, 0xFF, 0x00,
  0x01, 0xBF, 0xF8, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontEbrima40_B_0075[ 39] = { /* code 0075, LATIN SMALL LETTER U */
  0xFF, 0x00, 0xFF,
  0xFF, 0x00, 0xFF,
  0xFF, 0x00, 0xFF,
  0xFF, 0x00, 0xFF,
  0xFF, 0x00, 0xFF,
  0xFF, 0x00, 0xFF,
  0xFF, 0x00, 0xFF,
  0xFF, 0x00, 0xFF,
  0xFF, 0x00, 0xFF,
  0xFF, 0x83, 0xFF,
  0xBF, 0xFF, 0xFF,
  0x3F, 0xFD, 0xFF,
  0x0B, 0xF4, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontEbrima40_B_0078[ 52] = { /* code 0078, LATIN SMALL LETTER X */
  0xBF, 0xC0, 0x2F, 0xE0,
  0x3F, 0xE0, 0x3F, 0xC0,
  0x1F, 0xF0, 0xBF, 0x40,
  0x0B, 0xF8, 0xFE, 0x00,
  0x03, 0xFE, 0xFC, 0x00,
  0x01, 0xFF, 0xF4, 0x00,
  0x00, 0xFF, 0xF0, 0x00,
  0x01, 0xFF, 0xF8, 0x00,
  0x03, 0xFF, 0xFC, 0x00,
  0x0B, 0xF5, 0xFF, 0x00,
  0x1F, 0xF0, 0xFF, 0x40,
  0x3F, 0xD0, 0x7F, 0xC0,
  0xBF, 0xC0, 0x3F, 0xE0
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontEbrima40_B_CharInfo[4] = {
   {  10,  18,   2,  10,  13, acGUI_FontEbrima40_B_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  13,   1,  15,  14, acGUI_FontEbrima40_B_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{  12,  13,   1,  15,  15, acGUI_FontEbrima40_B_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{  14,  13,   0,  15,  14, acGUI_FontEbrima40_B_0078 } /* code 0078, LATIN SMALL LETTER X */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontEbrima40_B_Prop4 = {
   0x0078 /* first character */
  ,0x0078 /* last character  */
  ,&GUI_FontEbrima40_B_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontEbrima40_B_Prop3 = {
   0x0075 /* first character */
  ,0x0075 /* last character  */
  ,&GUI_FontEbrima40_B_CharInfo[  2] /* address of first character */
  ,&GUI_FontEbrima40_B_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontEbrima40_B_Prop2 = {
   0x0065 /* first character */
  ,0x0065 /* last character  */
  ,&GUI_FontEbrima40_B_CharInfo[  1] /* address of first character */
  ,&GUI_FontEbrima40_B_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontEbrima40_B_Prop1 = {
   0x004C /* first character */
  ,0x004C /* last character  */
  ,&GUI_FontEbrima40_B_CharInfo[  0] /* address of first character */
  ,&GUI_FontEbrima40_B_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontEbrima40_B = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,40 /* height of font  */
  ,40 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontEbrima40_B_Prop1}
  ,28 /* Baseline */
  ,13 /* Height of lowercase characters */
  ,18 /* Height of capital characters */
};

