/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Gill_Sans_MT30.c                                      *
* Font:        Gill Sans MT                                          *
* Height:      30                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  30                                           *
* Range disabled:       0000 - FFFF                                  *
* Character disabled:  0x3A (58)                                     *
* Character disabled:  0x3B (59)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x2E (46)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontGill_Sans_MT30;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_002E[  3] = { /* code 002E, FULL STOP */
  0xA0,
  0xF0,
  0xA0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0030[ 45] = { /* code 0030, DIGIT ZERO */
  0x07, 0xF4, 0x00,
  0x1F, 0xFD, 0x00,
  0x3D, 0x1F, 0x00,
  0x78, 0x0B, 0x40,
  0xB4, 0x07, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xB4, 0x07, 0x80,
  0x78, 0x0B, 0x40,
  0x3D, 0x1F, 0x00,
  0x1F, 0xFD, 0x00,
  0x07, 0xF4, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0031[ 15] = { /* code 0031, DIGIT ONE */
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0032[ 45] = { /* code 0032, DIGIT TWO */
  0x2F, 0xE0, 0x00,
  0xFF, 0xFC, 0x00,
  0x90, 0x3E, 0x00,
  0x00, 0x1F, 0x00,
  0x00, 0x0F, 0x00,
  0x00, 0x0F, 0x00,
  0x00, 0x1E, 0x00,
  0x00, 0x2D, 0x00,
  0x00, 0x7C, 0x00,
  0x00, 0xF0, 0x00,
  0x02, 0xD0, 0x00,
  0x07, 0x80, 0x00,
  0x0F, 0x00, 0x00,
  0x3F, 0xFF, 0xC0,
  0xBF, 0xFF, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0033[ 30] = { /* code 0033, DIGIT THREE */
  0x2F, 0xE0,
  0xFF, 0xFD,
  0x90, 0x3F,
  0x00, 0x0F,
  0x00, 0x0F,
  0x00, 0x2D,
  0x03, 0xF4,
  0x03, 0xFD,
  0x00, 0x7E,
  0x00, 0x0F,
  0x00, 0x0F,
  0x00, 0x0F,
  0x90, 0x3D,
  0xFF, 0xFC,
  0x7F, 0xD0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0034[ 45] = { /* code 0034, DIGIT FOUR */
  0x00, 0x03, 0x00,
  0x00, 0x0F, 0x00,
  0x00, 0x3F, 0x00,
  0x00, 0xBF, 0x00,
  0x01, 0xEF, 0x00,
  0x03, 0xCF, 0x00,
  0x0F, 0x0F, 0x00,
  0x3D, 0x0F, 0x00,
  0xBF, 0xFF, 0xF0,
  0xFF, 0xFF, 0xF0,
  0x00, 0x0F, 0x00,
  0x00, 0x0F, 0x00,
  0x00, 0x0F, 0x00,
  0x00, 0x0F, 0x00,
  0x00, 0x0F, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0035[ 30] = { /* code 0035, DIGIT FIVE */
  0x3F, 0xFC,
  0x3F, 0xFC,
  0x3C, 0x00,
  0x3C, 0x00,
  0x3C, 0x00,
  0x3C, 0x00,
  0x3F, 0xE0,
  0x3F, 0xFC,
  0x00, 0x7E,
  0x00, 0x1F,
  0x00, 0x0F,
  0x00, 0x1F,
  0x90, 0x7E,
  0xFF, 0xFC,
  0x6F, 0xE0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0036[ 45] = { /* code 0036, DIGIT SIX */
  0x00, 0x20, 0x00,
  0x00, 0xF8, 0x00,
  0x03, 0xF4, 0x00,
  0x0F, 0xC0, 0x00,
  0x2F, 0x00, 0x00,
  0x3C, 0x00, 0x00,
  0x7F, 0xF8, 0x00,
  0xBF, 0xFF, 0x00,
  0xF8, 0x0F, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF4, 0x03, 0xC0,
  0x7D, 0x0F, 0x80,
  0x2F, 0xFF, 0x00,
  0x07, 0xF8, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0037[ 45] = { /* code 0037, DIGIT SEVEN */
  0xFF, 0xFF, 0xC0,
  0xFF, 0xFF, 0x40,
  0x00, 0x0F, 0x00,
  0x00, 0x1E, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0x38, 0x00,
  0x00, 0xB4, 0x00,
  0x00, 0xF0, 0x00,
  0x02, 0xD0, 0x00,
  0x03, 0xC0, 0x00,
  0x07, 0x80, 0x00,
  0x0F, 0x00, 0x00,
  0x0F, 0x00, 0x00,
  0x2D, 0x00, 0x00,
  0x1C, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0038[ 45] = { /* code 0038, DIGIT EIGHT */
  0x0B, 0xF8, 0x00,
  0x3F, 0xFF, 0x00,
  0xF8, 0x0B, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0x7C, 0x0F, 0x40,
  0x2F, 0xFE, 0x00,
  0x3F, 0xFF, 0x00,
  0xBC, 0x0F, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0x7C, 0x0F, 0x80,
  0x3F, 0xFF, 0x00,
  0x0B, 0xF8, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill_Sans_MT30_0039[ 45] = { /* code 0039, DIGIT NINE */
  0x0B, 0xF4, 0x00,
  0x3F, 0xFE, 0x00,
  0xBC, 0x1F, 0x40,
  0xF0, 0x07, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xBC, 0x0B, 0xC0,
  0x3F, 0xFF, 0x80,
  0x0B, 0xFF, 0x40,
  0x00, 0x0F, 0x00,
  0x00, 0x3E, 0x00,
  0x00, 0xFC, 0x00,
  0x07, 0xF0, 0x00,
  0x0B, 0xC0, 0x00,
  0x03, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontGill_Sans_MT30_CharInfo[12] = {
   {   1,   1,   0,  23,   6, acGUI_FontGill_Sans_MT30_0020 } /* code 0020, SPACE */
  ,{   2,   3,   1,  20,   5, acGUI_FontGill_Sans_MT30_002E } /* code 002E, FULL STOP */
  ,{   9,  15,   1,   8,  11, acGUI_FontGill_Sans_MT30_0030 } /* code 0030, DIGIT ZERO */
  ,{   2,  15,   4,   8,  11, acGUI_FontGill_Sans_MT30_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  15,   1,   8,  11, acGUI_FontGill_Sans_MT30_0032 } /* code 0032, DIGIT TWO */
  ,{   8,  15,   1,   8,  11, acGUI_FontGill_Sans_MT30_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  15,   0,   8,  11, acGUI_FontGill_Sans_MT30_0034 } /* code 0034, DIGIT FOUR */
  ,{   8,  15,   1,   8,  11, acGUI_FontGill_Sans_MT30_0035 } /* code 0035, DIGIT FIVE */
  ,{   9,  15,   1,   8,  11, acGUI_FontGill_Sans_MT30_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  15,   1,   8,  11, acGUI_FontGill_Sans_MT30_0037 } /* code 0037, DIGIT SEVEN */
  ,{   9,  15,   1,   8,  11, acGUI_FontGill_Sans_MT30_0038 } /* code 0038, DIGIT EIGHT */
  ,{   9,  15,   1,   8,  11, acGUI_FontGill_Sans_MT30_0039 } /* code 0039, DIGIT NINE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontGill_Sans_MT30_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontGill_Sans_MT30_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontGill_Sans_MT30_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontGill_Sans_MT30_CharInfo[  1] /* address of first character */
  ,&GUI_FontGill_Sans_MT30_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontGill_Sans_MT30_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontGill_Sans_MT30_CharInfo[  0] /* address of first character */
  ,&GUI_FontGill_Sans_MT30_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontGill_Sans_MT30 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,30 /* height of font  */
  ,30 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontGill_Sans_MT30_Prop1}
  ,22 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,15 /* Height of capital characters */
};

