/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Gill16Sans_MT3_86.c                                   *
* Font:        Gill Sans MT                                          *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character disabled:  0x20 (32)                                     *
* Character enabled:   0x70 (112)                                    *
* Character disabled:  0x7F (127)                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontGill16Sans_MT3_86;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0021[ 10] = { /* code 0021, EXCLAMATION MARK */
  0x80,
  0xC0,
  0xC0,
  0xC0,
  0x80,
  0x80,
  0x40,
  0x00,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0022[  4] = { /* code 0022, QUOTATION MARK */
  0xCC,
  0xCC,
  0xCC,
  0x88
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0023[ 30] = { /* code 0023, NUMBER SIGN */
  0x03, 0x03, 0x00,
  0x06, 0x06, 0x00,
  0x05, 0x05, 0x00,
  0xFF, 0xFF, 0xC0,
  0x0C, 0x0C, 0x00,
  0x0C, 0x0C, 0x00,
  0xFF, 0xFF, 0xC0,
  0x24, 0x14, 0x00,
  0x24, 0x24, 0x00,
  0x30, 0x30, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0024[ 24] = { /* code 0024, DOLLAR SIGN */
  0x3F, 0x80,
  0xDC, 0x80,
  0xCC, 0x00,
  0xAC, 0x00,
  0x1F, 0x40,
  0x0C, 0x90,
  0x0C, 0x20,
  0x0C, 0x60,
  0x8C, 0xD0,
  0xBF, 0x40,
  0x0C, 0x00,
  0x0C, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0025[ 30] = { /* code 0025, PERCENT SIGN */
  0x7D, 0x06, 0x00,
  0xC3, 0x0C, 0x00,
  0xC3, 0x14, 0x00,
  0x7D, 0x30, 0x00,
  0x00, 0x90, 0x00,
  0x01, 0x80, 0x00,
  0x03, 0x1F, 0x40,
  0x05, 0x30, 0xC0,
  0x0C, 0x30, 0xC0,
  0x24, 0x1F, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0026[ 33] = { /* code 0026, AMPERSAND */
  0x00, 0x50, 0x00,
  0x0B, 0xFE, 0x00,
  0x2C, 0x03, 0x80,
  0x34, 0x01, 0xC0,
  0x30, 0x00, 0xC0,
  0x30, 0x00, 0xC0,
  0x30, 0x00, 0xC0,
  0x18, 0x02, 0x80,
  0x09, 0x06, 0x00,
  0x3F, 0x0F, 0xC0,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0027[  4] = { /* code 0027, APOSTROPHE */
  0xC0,
  0xC0,
  0xC0,
  0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0028[ 13] = { /* code 0028, LEFT PARENTHESIS */
  0x08,
  0x20,
  0x20,
  0x90,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0x90,
  0x20,
  0x20,
  0x08
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0029[ 13] = { /* code 0029, RIGHT PARENTHESIS */
  0x80,
  0x20,
  0x20,
  0x18,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x18,
  0x20,
  0x20,
  0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_002A[ 12] = { /* code 002A, ASTERISK */
  0x0C, 0x00,
  0xC8, 0xC0,
  0x2A, 0x00,
  0x29, 0x00,
  0xC8, 0xC0,
  0x0C, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_002B[ 14] = { /* code 002B, PLUS SIGN */
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00,
  0xFF, 0xFC,
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_002C[  4] = { /* code 002C, COMMA */
  0x80,
  0xC0,
  0xC0,
  0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_002D[  1] = { /* code 002D, HYPHEN-MINUS */
  0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_002E[  2] = { /* code 002E, FULL STOP */
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_002F[ 20] = { /* code 002F, SOLIDUS */
  0x00, 0xC0,
  0x01, 0x80,
  0x02, 0x40,
  0x03, 0x00,
  0x06, 0x00,
  0x09, 0x00,
  0x0C, 0x00,
  0x18, 0x00,
  0x24, 0x00,
  0x30, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0030[ 20] = { /* code 0030, DIGIT ZERO */
  0x1F, 0x40,
  0x30, 0xC0,
  0x90, 0x60,
  0xC0, 0x30,
  0xC0, 0x30,
  0xC0, 0x30,
  0xC0, 0x30,
  0x90, 0x60,
  0x30, 0xC0,
  0x1F, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0031[ 10] = { /* code 0031, DIGIT ONE */
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0032[ 20] = { /* code 0032, DIGIT TWO */
  0x6A, 0x40,
  0x80, 0x90,
  0x00, 0x30,
  0x00, 0x30,
  0x00, 0x60,
  0x00, 0xC0,
  0x03, 0x40,
  0x09, 0x00,
  0x24, 0x00,
  0xBF, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0033[ 20] = { /* code 0033, DIGIT THREE */
  0x7E, 0x00,
  0x82, 0xC0,
  0x00, 0xC0,
  0x01, 0xC0,
  0x0F, 0x40,
  0x02, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0,
  0x82, 0x80,
  0x7E, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0034[ 20] = { /* code 0034, DIGIT FOUR */
  0x00, 0xC0,
  0x02, 0xC0,
  0x03, 0xC0,
  0x0C, 0xC0,
  0x24, 0xC0,
  0x60, 0xC0,
  0xFF, 0xF0,
  0x00, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0035[ 20] = { /* code 0035, DIGIT FIVE */
  0xFF, 0xC0,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFD, 0x00,
  0x03, 0x00,
  0x00, 0x80,
  0x00, 0x80,
  0x82, 0x00,
  0x3D, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0036[ 20] = { /* code 0036, DIGIT SIX */
  0x06, 0x00,
  0x1D, 0x00,
  0x30, 0x00,
  0x50, 0x00,
  0xBE, 0x00,
  0xD1, 0x80,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0x91, 0x80,
  0x2E, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0037[ 20] = { /* code 0037, DIGIT SEVEN */
  0xFF, 0xF0,
  0x00, 0x20,
  0x00, 0x80,
  0x00, 0x80,
  0x02, 0x00,
  0x03, 0x00,
  0x09, 0x00,
  0x0C, 0x00,
  0x24, 0x00,
  0x20, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0038[ 20] = { /* code 0038, DIGIT EIGHT */
  0x2F, 0x80,
  0xA0, 0xA0,
  0xC0, 0x30,
  0xD0, 0x70,
  0x7A, 0xD0,
  0xD0, 0x70,
  0xC0, 0x30,
  0xC0, 0x30,
  0x90, 0x60,
  0x2F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0039[ 20] = { /* code 0039, DIGIT NINE */
  0x2F, 0x00,
  0x91, 0xC0,
  0x80, 0xC0,
  0xC0, 0x80,
  0x90, 0xC0,
  0x2F, 0xC0,
  0x00, 0x80,
  0x02, 0x00,
  0x1D, 0x00,
  0x24, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_003A[  6] = { /* code 003A, COLON */
  0xC0,
  0xC0,
  0x00,
  0x00,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_003B[  8] = { /* code 003B, SEMICOLON */
  0xC0,
  0xC0,
  0x00,
  0x00,
  0x80,
  0xC0,
  0xC0,
  0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_003C[ 14] = { /* code 003C, LESS-THAN SIGN */
  0x00, 0x1C,
  0x01, 0xE0,
  0x2E, 0x00,
  0xF0, 0x00,
  0x2E, 0x00,
  0x01, 0xE0,
  0x00, 0x1C
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_003D[  8] = { /* code 003D, EQUALS SIGN */
  0xFF, 0xFC,
  0x00, 0x00,
  0x00, 0x00,
  0xFF, 0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_003E[ 14] = { /* code 003E, GREATER-THAN SIGN */
  0xD0, 0x00,
  0x2D, 0x00,
  0x02, 0xE0,
  0x00, 0x3C,
  0x02, 0xE0,
  0x2D, 0x00,
  0xD0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_003F[ 10] = { /* code 003F, QUESTION MARK */
  0x90,
  0x30,
  0x30,
  0x70,
  0xE0,
  0xC0,
  0x80,
  0x00,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0040[ 39] = { /* code 0040, COMMERCIAL AT */
  0x01, 0xBF, 0x80,
  0x0B, 0x40, 0x74,
  0x28, 0x00, 0x0C,
  0x30, 0x7D, 0xC6,
  0x90, 0xC3, 0xC3,
  0xC2, 0x41, 0x83,
  0xC3, 0x01, 0x83,
  0xC3, 0x02, 0x49,
  0xC2, 0x47, 0x1C,
  0xA0, 0xF7, 0xE0,
  0x34, 0x00, 0x0A,
  0x0E, 0x00, 0x78,
  0x01, 0xFF, 0x90
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0041[ 30] = { /* code 0041, LATIN CAPITAL LETTER A */
  0x00, 0x80, 0x00,
  0x00, 0xC0, 0x00,
  0x02, 0xA0, 0x00,
  0x03, 0x30, 0x00,
  0x09, 0x18, 0x00,
  0x0C, 0x0C, 0x00,
  0x1F, 0xFD, 0x00,
  0x30, 0x03, 0x00,
  0x60, 0x02, 0x40,
  0xC0, 0x00, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0042[ 20] = { /* code 0042, LATIN CAPITAL LETTER B */
  0xFF, 0x00,
  0xC1, 0xC0,
  0xC0, 0xC0,
  0xC1, 0x80,
  0xFF, 0x40,
  0xC0, 0x60,
  0xC0, 0x30,
  0xC0, 0x30,
  0xC0, 0x60,
  0xFF, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0043[ 20] = { /* code 0043, LATIN CAPITAL LETTER C */
  0x07, 0xF8,
  0x18, 0x06,
  0x30, 0x00,
  0x80, 0x00,
  0x80, 0x00,
  0x80, 0x00,
  0x80, 0x00,
  0x20, 0x00,
  0x18, 0x06,
  0x02, 0xA8
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0044[ 30] = { /* code 0044, LATIN CAPITAL LETTER D */
  0xFF, 0xE0, 0x00,
  0xC0, 0x1D, 0x00,
  0xC0, 0x03, 0x00,
  0xC0, 0x01, 0x80,
  0xC0, 0x00, 0x80,
  0xC0, 0x00, 0x80,
  0xC0, 0x01, 0x80,
  0xC0, 0x03, 0x00,
  0xC0, 0x1D, 0x00,
  0xFF, 0xE0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0045[ 20] = { /* code 0045, LATIN CAPITAL LETTER E */
  0xFF, 0xC0,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFF, 0xC0,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFF, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0046[ 20] = { /* code 0046, LATIN CAPITAL LETTER F */
  0xFF, 0xC0,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFF, 0xC0,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0047[ 20] = { /* code 0047, LATIN CAPITAL LETTER G */
  0x03, 0xF9,
  0x18, 0x06,
  0x20, 0x00,
  0x40, 0x00,
  0x80, 0x00,
  0x80, 0x3F,
  0x40, 0x03,
  0x20, 0x03,
  0x18, 0x07,
  0x07, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0048[ 20] = { /* code 0048, LATIN CAPITAL LETTER H */
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xFF, 0xFF,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0049[ 10] = { /* code 0049, LATIN CAPITAL LETTER I */
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_004A[ 13] = { /* code 004A, LATIN CAPITAL LETTER J */
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x1C,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_004B[ 20] = { /* code 004B, LATIN CAPITAL LETTER K */
  0xC0, 0x24,
  0xC0, 0x90,
  0xC2, 0x40,
  0xC9, 0x00,
  0xE4, 0x00,
  0xE4, 0x00,
  0xC6, 0x00,
  0xC1, 0x80,
  0xC0, 0x20,
  0xC0, 0x09
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_004C[ 20] = { /* code 004C, LATIN CAPITAL LETTER L */
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFF, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_004D[ 30] = { /* code 004D, LATIN CAPITAL LETTER M */
  0x80, 0x00, 0x80,
  0xE0, 0x02, 0xC0,
  0xD8, 0x09, 0xC0,
  0xC2, 0x20, 0xC0,
  0xC0, 0xC0, 0xC0,
  0xC0, 0x00, 0xC0,
  0xC0, 0x00, 0xC0,
  0xC0, 0x00, 0xC0,
  0xC0, 0x00, 0xC0,
  0xC0, 0x00, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_004E[ 30] = { /* code 004E, LATIN CAPITAL LETTER N */
  0xC0, 0x00, 0xC0,
  0xE0, 0x00, 0xC0,
  0xC8, 0x00, 0xC0,
  0xC2, 0x00, 0xC0,
  0xC1, 0x40, 0xC0,
  0xC0, 0x90, 0xC0,
  0xC0, 0x20, 0xC0,
  0xC0, 0x08, 0xC0,
  0xC0, 0x02, 0xC0,
  0xC0, 0x01, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_004F[ 30] = { /* code 004F, LATIN CAPITAL LETTER O */
  0x07, 0xFD, 0x00,
  0x1D, 0x07, 0x40,
  0x30, 0x00, 0xC0,
  0x90, 0x00, 0x60,
  0x80, 0x00, 0x20,
  0x80, 0x00, 0x20,
  0x90, 0x00, 0x60,
  0x30, 0x00, 0xC0,
  0x1D, 0x07, 0x40,
  0x07, 0xFD, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0050[ 20] = { /* code 0050, LATIN CAPITAL LETTER P */
  0xFF, 0x40,
  0xC0, 0xD0,
  0xC0, 0x60,
  0xC0, 0x60,
  0xC0, 0xD0,
  0xFF, 0x40,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0051[ 36] = { /* code 0051, LATIN CAPITAL LETTER Q */
  0x07, 0xFD, 0x00,
  0x1D, 0x07, 0x40,
  0x30, 0x00, 0xC0,
  0x90, 0x00, 0x60,
  0x80, 0x00, 0x20,
  0x80, 0x00, 0x20,
  0x90, 0x00, 0x60,
  0x30, 0x00, 0x80,
  0x2D, 0x07, 0x00,
  0x07, 0xFC, 0x00,
  0x00, 0x74, 0x00,
  0x00, 0x0B, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0052[ 20] = { /* code 0052, LATIN CAPITAL LETTER R */
  0xFF, 0x40,
  0xC1, 0xD0,
  0xC0, 0x60,
  0xC0, 0x60,
  0xC0, 0xC0,
  0xFF, 0x00,
  0xC2, 0x40,
  0xC0, 0x80,
  0xC0, 0x30,
  0xC0, 0x18
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0053[ 20] = { /* code 0053, LATIN CAPITAL LETTER S */
  0x2F, 0x40,
  0x90, 0x80,
  0xC0, 0x00,
  0xC0, 0x00,
  0x38, 0x00,
  0x07, 0x00,
  0x00, 0xC0,
  0x40, 0xC0,
  0x91, 0x80,
  0x2F, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0054[ 20] = { /* code 0054, LATIN CAPITAL LETTER T */
  0xFF, 0xFC,
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00,
  0x03, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0055[ 20] = { /* code 0055, LATIN CAPITAL LETTER U */
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0xC0, 0x03,
  0x74, 0x1D,
  0x1F, 0xF4
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0056[ 30] = { /* code 0056, LATIN CAPITAL LETTER V */
  0x80, 0x01, 0x80,
  0x20, 0x03, 0x40,
  0x20, 0x07, 0x00,
  0x08, 0x0D, 0x00,
  0x08, 0x0C, 0x00,
  0x06, 0x24, 0x00,
  0x03, 0x70, 0x00,
  0x01, 0xD0, 0x00,
  0x00, 0x80, 0x00,
  0x00, 0x40, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0057[ 40] = { /* code 0057, LATIN CAPITAL LETTER W */
  0x80, 0x03, 0x00, 0x0C,
  0x20, 0x07, 0x40, 0x24,
  0x20, 0x0E, 0xC0, 0x30,
  0x0C, 0x0C, 0xC0, 0xD0,
  0x09, 0x24, 0x61, 0xC0,
  0x03, 0x30, 0x33, 0x40,
  0x02, 0xA0, 0x2B, 0x00,
  0x00, 0xD0, 0x1E, 0x00,
  0x00, 0x80, 0x0C, 0x00,
  0x00, 0x40, 0x04, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0058[ 30] = { /* code 0058, LATIN CAPITAL LETTER X */
  0x90, 0x00, 0x60,
  0x24, 0x01, 0x80,
  0x09, 0x06, 0x00,
  0x02, 0x08, 0x00,
  0x00, 0xA0, 0x00,
  0x00, 0xB0, 0x00,
  0x02, 0x0C, 0x00,
  0x09, 0x06, 0x00,
  0x24, 0x01, 0x80,
  0x90, 0x00, 0x60
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0059[ 20] = { /* code 0059, LATIN CAPITAL LETTER Y */
  0x90, 0x06,
  0x24, 0x0C,
  0x0C, 0x24,
  0x03, 0x60,
  0x00, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_005A[ 30] = { /* code 005A, LATIN CAPITAL LETTER Z */
  0xFF, 0xFF, 0x80,
  0x00, 0x01, 0x00,
  0x00, 0x04, 0x00,
  0x00, 0x10, 0x00,
  0x00, 0x50, 0x00,
  0x00, 0x40, 0x00,
  0x02, 0x00, 0x00,
  0x08, 0x00, 0x00,
  0x20, 0x00, 0x00,
  0xBF, 0xFF, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_005B[ 13] = { /* code 005B, LEFT SQUARE BRACKET */
  0xFC,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_005C[ 20] = { /* code 005C, REVERSE SOLIDUS */
  0x30, 0x00,
  0x24, 0x00,
  0x18, 0x00,
  0x0C, 0x00,
  0x09, 0x00,
  0x06, 0x00,
  0x03, 0x00,
  0x02, 0x40,
  0x01, 0x80,
  0x00, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_005D[ 13] = { /* code 005D, RIGHT SQUARE BRACKET */
  0xFC,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_005E[ 10] = { /* code 005E, CIRCUMFLEX ACCENT */
  0x0C, 0x00,
  0x2E, 0x00,
  0x33, 0x00,
  0x62, 0x40,
  0xC0, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_005F[  2] = { /* code 005F, LOW LINE */
  0xFF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0060[  2] = { /* code 0060, GRAVE ACCENT */
  0x80,
  0x20
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0061[ 12] = { /* code 0061, LATIN SMALL LETTER A */
  0x7D, 0x00,
  0x43, 0x00,
  0x1F, 0x00,
  0xA3, 0x00,
  0xC3, 0x00,
  0x7B, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0062[ 20] = { /* code 0062, LATIN SMALL LETTER B */
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xFF, 0x00,
  0xD1, 0x80,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xC1, 0x80,
  0xBE, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0063[  6] = { /* code 0063, LATIN SMALL LETTER C */
  0x3F,
  0x90,
  0x80,
  0x80,
  0x90,
  0x3F
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0064[ 20] = { /* code 0064, LATIN SMALL LETTER D */
  0x00, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0,
  0x2F, 0xC0,
  0xA0, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0x90, 0xC0,
  0x2F, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0065[ 12] = { /* code 0065, LATIN SMALL LETTER E */
  0x2F, 0x00,
  0x91, 0x80,
  0xFF, 0xC0,
  0xC0, 0x00,
  0x90, 0x00,
  0x2F, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0066[ 10] = { /* code 0066, LATIN SMALL LETTER F */
  0x0F,
  0x24,
  0x30,
  0x30,
  0xFC,
  0x30,
  0x30,
  0x30,
  0x30,
  0x30
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0067[ 18] = { /* code 0067, LATIN SMALL LETTER G */
  0x3F, 0xF0,
  0xD1, 0x80,
  0xD1, 0xC0,
  0x7F, 0x40,
  0x30, 0x00,
  0x3E, 0x80,
  0xD0, 0x70,
  0xD0, 0x70,
  0x3F, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0068[ 20] = { /* code 0068, LATIN SMALL LETTER H */
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xDF, 0x40,
  0xD1, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0069[  9] = { /* code 0069, LATIN SMALL LETTER I */
  0xC0,
  0x00,
  0x00,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_006A[ 12] = { /* code 006A, LATIN SMALL LETTER J */
  0x30,
  0x00,
  0x00,
  0x30,
  0x30,
  0x30,
  0x30,
  0x30,
  0x30,
  0x30,
  0x70,
  0x90
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_006B[ 20] = { /* code 006B, LATIN SMALL LETTER K */
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC2, 0x40,
  0xC8, 0x00,
  0xE4, 0x00,
  0xC8, 0x00,
  0xC2, 0x40,
  0xC0, 0x90
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_006C[ 10] = { /* code 006C, LATIN SMALL LETTER L */
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_006D[ 18] = { /* code 006D, LATIN SMALL LETTER M */
  0xFF, 0xAF, 0x40,
  0xC1, 0xC1, 0xC0,
  0xC0, 0xC0, 0xC0,
  0xC0, 0xC0, 0xC0,
  0xC0, 0xC0, 0xC0,
  0xC0, 0xC0, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_006E[ 12] = { /* code 006E, LATIN SMALL LETTER N */
  0xDF, 0x40,
  0xD1, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_006F[ 12] = { /* code 006F, LATIN SMALL LETTER O */
  0x2F, 0x80,
  0x90, 0x60,
  0x80, 0x20,
  0x80, 0x20,
  0x90, 0x60,
  0x2F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0070[ 18] = { /* code 0070, LATIN SMALL LETTER P */
  0xFE, 0x00,
  0xC1, 0x80,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xC1, 0x80,
  0xFE, 0x00,
  0xC0, 0x00,
  0xC0, 0x00,
  0xC0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0071[ 18] = { /* code 0071, LATIN SMALL LETTER Q */
  0x2F, 0xC0,
  0x90, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0x90, 0xC0,
  0x2F, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0,
  0x00, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0072[  6] = { /* code 0072, LATIN SMALL LETTER R */
  0xDE,
  0xD1,
  0xC0,
  0xC0,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0073[  6] = { /* code 0073, LATIN SMALL LETTER S */
  0x7E,
  0xC0,
  0xB0,
  0x0E,
  0x03,
  0xA9
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0074[ 16] = { /* code 0074, LATIN SMALL LETTER T */
  0x10, 0x00,
  0x30, 0x00,
  0xBF, 0xC0,
  0x30, 0x00,
  0x30, 0x00,
  0x30, 0x00,
  0x30, 0x00,
  0x1F, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0075[ 12] = { /* code 0075, LATIN SMALL LETTER U */
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xC0, 0xC0,
  0xD1, 0xC0,
  0x7E, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0076[ 12] = { /* code 0076, LATIN SMALL LETTER V */
  0xC0, 0xC0,
  0x62, 0x40,
  0x33, 0x00,
  0x2E, 0x00,
  0x0C, 0x00,
  0x04, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0077[ 18] = { /* code 0077, LATIN SMALL LETTER W */
  0xC0, 0xC0, 0xC0,
  0x61, 0xD2, 0x40,
  0x33, 0x73, 0x00,
  0x2E, 0x2E, 0x00,
  0x0C, 0x0C, 0x00,
  0x04, 0x04, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0078[ 12] = { /* code 0078, LATIN SMALL LETTER X */
  0x90, 0x60,
  0x25, 0x80,
  0x0F, 0x00,
  0x0F, 0x00,
  0x20, 0x80,
  0x90, 0x60
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_0079[ 18] = { /* code 0079, LATIN SMALL LETTER Y */
  0xC0, 0x60,
  0x60, 0xC0,
  0x31, 0x80,
  0x1B, 0x00,
  0x0D, 0x00,
  0x0C, 0x00,
  0x24, 0x00,
  0x30, 0x00,
  0x80, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_007A[ 12] = { /* code 007A, LATIN SMALL LETTER Z */
  0xFF, 0xE0,
  0x00, 0x80,
  0x02, 0x00,
  0x08, 0x00,
  0x20, 0x00,
  0xBF, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_007B[ 13] = { /* code 007B, LEFT CURLY BRACKET */
  0x1C,
  0x30,
  0x30,
  0x30,
  0x30,
  0x70,
  0xD0,
  0x70,
  0x30,
  0x30,
  0x30,
  0x30,
  0x1C
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_007C[ 13] = { /* code 007C, VERTICAL LINE */
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0,
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_007D[ 13] = { /* code 007D, RIGHT CURLY BRACKET */
  0xD0,
  0x30,
  0x30,
  0x30,
  0x30,
  0x34,
  0x1C,
  0x34,
  0x30,
  0x30,
  0x30,
  0x30,
  0xD0
};

GUI_CONST_STORAGE unsigned char acGUI_FontGill16Sans_MT3_86_007E[  4] = { /* code 007E, TILDE */
  0xBE, 0x08,
  0x82, 0xF8
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontGill16Sans_MT3_86_CharInfo[95] = {
   {   1,   1,   0,  13,   4, acGUI_FontGill16Sans_MT3_86_0020 } /* code 0020, SPACE */
  ,{   1,  10,   1,   3,   4, acGUI_FontGill16Sans_MT3_86_0021 } /* code 0021, EXCLAMATION MARK */
  ,{   3,   4,   1,   3,   5, acGUI_FontGill16Sans_MT3_86_0022 } /* code 0022, QUOTATION MARK */
  ,{   9,  10,   0,   3,   8, acGUI_FontGill16Sans_MT3_86_0023 } /* code 0023, NUMBER SIGN */
  ,{   6,  12,   1,   3,   8, acGUI_FontGill16Sans_MT3_86_0024 } /* code 0024, DOLLAR SIGN */
  ,{   9,  10,   0,   3,   9, acGUI_FontGill16Sans_MT3_86_0025 } /* code 0025, PERCENT SIGN */
  ,{  10,  11,   0,   3,  10, acGUI_FontGill16Sans_MT3_86_0026 } /* code 0026, AMPERSAND */
  ,{   1,   4,   1,   3,   3, acGUI_FontGill16Sans_MT3_86_0027 } /* code 0027, APOSTROPHE */
  ,{   3,  13,   1,   3,   5, acGUI_FontGill16Sans_MT3_86_0028 } /* code 0028, LEFT PARENTHESIS */
  ,{   3,  13,   1,   3,   5, acGUI_FontGill16Sans_MT3_86_0029 } /* code 0029, RIGHT PARENTHESIS */
  ,{   5,   6,   0,   3,   6, acGUI_FontGill16Sans_MT3_86_002A } /* code 002A, ASTERISK */
  ,{   7,   7,   0,   4,   8, acGUI_FontGill16Sans_MT3_86_002B } /* code 002B, PLUS SIGN */
  ,{   1,   4,   1,  11,   3, acGUI_FontGill16Sans_MT3_86_002C } /* code 002C, COMMA */
  ,{   3,   1,   1,   9,   5, acGUI_FontGill16Sans_MT3_86_002D } /* code 002D, HYPHEN-MINUS */
  ,{   1,   2,   1,  11,   3, acGUI_FontGill16Sans_MT3_86_002E } /* code 002E, FULL STOP */
  ,{   6,  10,  -1,   3,   4, acGUI_FontGill16Sans_MT3_86_002F } /* code 002F, SOLIDUS */
  ,{   6,  10,   0,   3,   7, acGUI_FontGill16Sans_MT3_86_0030 } /* code 0030, DIGIT ZERO */
  ,{   1,  10,   3,   3,   7, acGUI_FontGill16Sans_MT3_86_0031 } /* code 0031, DIGIT ONE */
  ,{   6,  10,   0,   3,   7, acGUI_FontGill16Sans_MT3_86_0032 } /* code 0032, DIGIT TWO */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0033 } /* code 0033, DIGIT THREE */
  ,{   6,  10,   0,   3,   7, acGUI_FontGill16Sans_MT3_86_0034 } /* code 0034, DIGIT FOUR */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0035 } /* code 0035, DIGIT FIVE */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0036 } /* code 0036, DIGIT SIX */
  ,{   7,  10,   0,   3,   7, acGUI_FontGill16Sans_MT3_86_0037 } /* code 0037, DIGIT SEVEN */
  ,{   6,  10,   0,   3,   7, acGUI_FontGill16Sans_MT3_86_0038 } /* code 0038, DIGIT EIGHT */
  ,{   6,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0039 } /* code 0039, DIGIT NINE */
  ,{   1,   6,   1,   7,   3, acGUI_FontGill16Sans_MT3_86_003A } /* code 003A, COLON */
  ,{   1,   8,   1,   7,   3, acGUI_FontGill16Sans_MT3_86_003B } /* code 003B, SEMICOLON */
  ,{   7,   7,   1,   5,   8, acGUI_FontGill16Sans_MT3_86_003C } /* code 003C, LESS-THAN SIGN */
  ,{   7,   4,   1,   6,   8, acGUI_FontGill16Sans_MT3_86_003D } /* code 003D, EQUALS SIGN */
  ,{   7,   7,   1,   5,   8, acGUI_FontGill16Sans_MT3_86_003E } /* code 003E, GREATER-THAN SIGN */
  ,{   2,  10,   1,   3,   5, acGUI_FontGill16Sans_MT3_86_003F } /* code 003F, QUESTION MARK */
  ,{  12,  13,   1,   3,  14, acGUI_FontGill16Sans_MT3_86_0040 } /* code 0040, COMMERCIAL AT */
  ,{   9,  10,   0,   3,   9, acGUI_FontGill16Sans_MT3_86_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   6,  10,   1,   3,   8, acGUI_FontGill16Sans_MT3_86_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   8,  10,   1,   3,  10, acGUI_FontGill16Sans_MT3_86_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   9,  10,   1,   3,  11, acGUI_FontGill16Sans_MT3_86_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   8,  10,   1,   3,  10, acGUI_FontGill16Sans_MT3_86_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   8,  10,   1,   3,  10, acGUI_FontGill16Sans_MT3_86_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   1,  10,   1,   3,   4, acGUI_FontGill16Sans_MT3_86_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   3,  13,  -1,   3,   4, acGUI_FontGill16Sans_MT3_86_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   8,  10,   1,   3,   9, acGUI_FontGill16Sans_MT3_86_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   6,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{   9,  10,   1,   3,  11, acGUI_FontGill16Sans_MT3_86_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   9,  10,   1,   3,  11, acGUI_FontGill16Sans_MT3_86_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  10,  10,   1,   3,  12, acGUI_FontGill16Sans_MT3_86_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   6,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  10,  12,   1,   3,  12, acGUI_FontGill16Sans_MT3_86_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   7,  10,   1,   3,   8, acGUI_FontGill16Sans_MT3_86_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   7,  10,   0,   3,   8, acGUI_FontGill16Sans_MT3_86_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   8,  10,   1,   3,  10, acGUI_FontGill16Sans_MT3_86_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   9,  10,   0,   3,   8, acGUI_FontGill16Sans_MT3_86_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  15,  10,   0,   3,  15, acGUI_FontGill16Sans_MT3_86_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  10,  10,   0,   3,  10, acGUI_FontGill16Sans_MT3_86_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   8,  10,   0,   3,   8, acGUI_FontGill16Sans_MT3_86_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   9,  10,   0,   3,   9, acGUI_FontGill16Sans_MT3_86_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{   3,  13,   1,   3,   5, acGUI_FontGill16Sans_MT3_86_005B } /* code 005B, LEFT SQUARE BRACKET */
  ,{   6,  10,  -1,   3,   4, acGUI_FontGill16Sans_MT3_86_005C } /* code 005C, REVERSE SOLIDUS */
  ,{   3,  13,   0,   3,   5, acGUI_FontGill16Sans_MT3_86_005D } /* code 005D, RIGHT SQUARE BRACKET */
  ,{   5,   5,   0,   3,   7, acGUI_FontGill16Sans_MT3_86_005E } /* code 005E, CIRCUMFLEX ACCENT */
  ,{   8,   1,   0,  15,   8, acGUI_FontGill16Sans_MT3_86_005F } /* code 005F, LOW LINE */
  ,{   2,   2,   1,   3,   5, acGUI_FontGill16Sans_MT3_86_0060 } /* code 0060, GRAVE ACCENT */
  ,{   5,   6,   1,   7,   6, acGUI_FontGill16Sans_MT3_86_0061 } /* code 0061, LATIN SMALL LETTER A */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0062 } /* code 0062, LATIN SMALL LETTER B */
  ,{   4,   6,   1,   7,   6, acGUI_FontGill16Sans_MT3_86_0063 } /* code 0063, LATIN SMALL LETTER C */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0064 } /* code 0064, LATIN SMALL LETTER D */
  ,{   5,   6,   1,   7,   7, acGUI_FontGill16Sans_MT3_86_0065 } /* code 0065, LATIN SMALL LETTER E */
  ,{   4,  10,   0,   3,   4, acGUI_FontGill16Sans_MT3_86_0066 } /* code 0066, LATIN SMALL LETTER F */
  ,{   6,   9,   0,   7,   6, acGUI_FontGill16Sans_MT3_86_0067 } /* code 0067, LATIN SMALL LETTER G */
  ,{   5,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_0068 } /* code 0068, LATIN SMALL LETTER H */
  ,{   1,   9,   1,   4,   3, acGUI_FontGill16Sans_MT3_86_0069 } /* code 0069, LATIN SMALL LETTER I */
  ,{   2,  12,   0,   4,   3, acGUI_FontGill16Sans_MT3_86_006A } /* code 006A, LATIN SMALL LETTER J */
  ,{   6,  10,   1,   3,   7, acGUI_FontGill16Sans_MT3_86_006B } /* code 006B, LATIN SMALL LETTER K */
  ,{   1,  10,   1,   3,   3, acGUI_FontGill16Sans_MT3_86_006C } /* code 006C, LATIN SMALL LETTER L */
  ,{   9,   6,   1,   7,  11, acGUI_FontGill16Sans_MT3_86_006D } /* code 006D, LATIN SMALL LETTER M */
  ,{   5,   6,   1,   7,   7, acGUI_FontGill16Sans_MT3_86_006E } /* code 006E, LATIN SMALL LETTER N */
  ,{   6,   6,   1,   7,   8, acGUI_FontGill16Sans_MT3_86_006F } /* code 006F, LATIN SMALL LETTER O */
  ,{   5,   9,   1,   7,   7, acGUI_FontGill16Sans_MT3_86_0070 } /* code 0070, LATIN SMALL LETTER P */
  ,{   5,   9,   1,   7,   7, acGUI_FontGill16Sans_MT3_86_0071 } /* code 0071, LATIN SMALL LETTER Q */
  ,{   4,   6,   1,   7,   6, acGUI_FontGill16Sans_MT3_86_0072 } /* code 0072, LATIN SMALL LETTER R */
  ,{   4,   6,   0,   7,   5, acGUI_FontGill16Sans_MT3_86_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{   5,   8,   0,   5,   5, acGUI_FontGill16Sans_MT3_86_0074 } /* code 0074, LATIN SMALL LETTER T */
  ,{   5,   6,   1,   7,   7, acGUI_FontGill16Sans_MT3_86_0075 } /* code 0075, LATIN SMALL LETTER U */
  ,{   5,   6,   0,   7,   6, acGUI_FontGill16Sans_MT3_86_0076 } /* code 0076, LATIN SMALL LETTER V */
  ,{   9,   6,   0,   7,  10, acGUI_FontGill16Sans_MT3_86_0077 } /* code 0077, LATIN SMALL LETTER W */
  ,{   6,   6,   0,   7,   7, acGUI_FontGill16Sans_MT3_86_0078 } /* code 0078, LATIN SMALL LETTER X */
  ,{   6,   9,   0,   7,   6, acGUI_FontGill16Sans_MT3_86_0079 } /* code 0079, LATIN SMALL LETTER Y */
  ,{   6,   6,   0,   7,   6, acGUI_FontGill16Sans_MT3_86_007A } /* code 007A, LATIN SMALL LETTER Z */
  ,{   3,  13,   1,   3,   5, acGUI_FontGill16Sans_MT3_86_007B } /* code 007B, LEFT CURLY BRACKET */
  ,{   1,  13,   1,   3,   4, acGUI_FontGill16Sans_MT3_86_007C } /* code 007C, VERTICAL LINE */
  ,{   3,  13,   1,   3,   5, acGUI_FontGill16Sans_MT3_86_007D } /* code 007D, RIGHT CURLY BRACKET */
  ,{   7,   2,   1,   7,   8, acGUI_FontGill16Sans_MT3_86_007E } /* code 007E, TILDE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontGill16Sans_MT3_86_Prop1 = {
   0x0020 /* first character */
  ,0x007E /* last character  */
  ,&GUI_FontGill16Sans_MT3_86_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontGill16Sans_MT3_86 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontGill16Sans_MT3_86_Prop1}
  ,13 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

