/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: MStiffHei_HKS20.c                                     *
* Font:        ÃÉÄÉ¼ò³¬¸ÕºÚ                                          *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontMStiffHei_HKS20;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0030[ 36] = { /* code 0030, DIGIT ZERO */
  0x15, 0x55, 0x40,
  0x7F, 0xFF, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7E, 0x1F, 0x80,
  0x7F, 0xFF, 0x80,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0031[ 24] = { /* code 0031, DIGIT ONE */
  0x55, 0x40,
  0xBF, 0xC0,
  0x0B, 0xC0,
  0x0B, 0xC0,
  0x0B, 0xC0,
  0x0B, 0xC0,
  0x0B, 0xC0,
  0x0B, 0xC0,
  0x0B, 0xC0,
  0x0B, 0xC0,
  0x0B, 0xC0,
  0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0032[ 36] = { /* code 0032, DIGIT TWO */
  0x15, 0x55, 0x00,
  0x7F, 0xFF, 0x00,
  0x00, 0x1F, 0x00,
  0x00, 0x1F, 0x00,
  0x00, 0x1F, 0x00,
  0x00, 0x7F, 0x00,
  0x01, 0xFD, 0x00,
  0x07, 0xF4, 0x00,
  0x1F, 0xD0, 0x00,
  0x7F, 0x80, 0x00,
  0x7F, 0xFF, 0x80,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0033[ 36] = { /* code 0033, DIGIT THREE */
  0x15, 0x55, 0x40,
  0x7F, 0xFF, 0x80,
  0x00, 0x0F, 0x80,
  0x00, 0x0F, 0x80,
  0x00, 0x0F, 0x80,
  0x0F, 0xFE, 0x00,
  0x05, 0x6F, 0x40,
  0x00, 0x0F, 0x80,
  0x00, 0x0F, 0x80,
  0x00, 0x1F, 0x80,
  0x7F, 0xFF, 0x80,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0034[ 36] = { /* code 0034, DIGIT FOUR */
  0x00, 0x15, 0x00,
  0x00, 0x3E, 0x00,
  0x00, 0xFE, 0x00,
  0x02, 0xFE, 0x00,
  0x03, 0x7E, 0x00,
  0x0E, 0x3E, 0x00,
  0x2C, 0x3E, 0x00,
  0x74, 0x3F, 0x00,
  0xBF, 0xFF, 0xC0,
  0x00, 0x3F, 0x00,
  0x00, 0x3E, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0035[ 36] = { /* code 0035, DIGIT FIVE */
  0x14, 0x55, 0x40,
  0x3E, 0xFF, 0x80,
  0x3D, 0x00, 0x00,
  0x3D, 0x00, 0x00,
  0x3E, 0x55, 0x00,
  0x3F, 0xFF, 0x80,
  0x00, 0x0F, 0x80,
  0x00, 0x0F, 0x80,
  0x00, 0x0F, 0x80,
  0x00, 0x1F, 0x80,
  0x3F, 0xFF, 0x80,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0036[ 36] = { /* code 0036, DIGIT SIX */
  0x15, 0x55, 0x40,
  0x7F, 0xFF, 0x80,
  0x7D, 0x00, 0x00,
  0x7D, 0x00, 0x00,
  0x7E, 0x55, 0x40,
  0x7F, 0xFF, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7E, 0x1F, 0x80,
  0x7F, 0xFF, 0x80,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0037[ 36] = { /* code 0037, DIGIT SEVEN */
  0x15, 0x55, 0x40,
  0x7F, 0xFF, 0x80,
  0x00, 0x1F, 0x80,
  0x00, 0x2F, 0x00,
  0x00, 0x3F, 0x00,
  0x00, 0x7E, 0x00,
  0x00, 0xFC, 0x00,
  0x00, 0xFC, 0x00,
  0x02, 0xF4, 0x00,
  0x03, 0xF0, 0x00,
  0x07, 0xE0, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0038[ 36] = { /* code 0038, DIGIT EIGHT */
  0x15, 0x55, 0x40,
  0x3F, 0xFF, 0x80,
  0x3D, 0x0F, 0x80,
  0x3D, 0x0F, 0x80,
  0x3E, 0x1F, 0x40,
  0x0F, 0xFE, 0x00,
  0x3E, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7E, 0x0F, 0x80,
  0x7F, 0xFF, 0x80,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontMStiffHei_HKS20_0039[ 36] = { /* code 0039, DIGIT NINE */
  0x15, 0x55, 0x40,
  0x7F, 0xFF, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7D, 0x0F, 0x80,
  0x7F, 0xFF, 0x80,
  0x15, 0x5F, 0x80,
  0x00, 0x0F, 0x80,
  0x00, 0x0F, 0x80,
  0x3F, 0xFF, 0x80,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontMStiffHei_HKS20_CharInfo[10] = {
   {   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  12,   1,   6,  10, acGUI_FontMStiffHei_HKS20_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0033 } /* code 0033, DIGIT THREE */
  ,{   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0035 } /* code 0035, DIGIT FIVE */
  ,{   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0037 } /* code 0037, DIGIT SEVEN */
  ,{   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0038 } /* code 0038, DIGIT EIGHT */
  ,{   9,  12,   0,   6,  10, acGUI_FontMStiffHei_HKS20_0039 } /* code 0039, DIGIT NINE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontMStiffHei_HKS20_Prop1 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontMStiffHei_HKS20_CharInfo[  0] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontMStiffHei_HKS20 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontMStiffHei_HKS20_Prop1}
  ,18 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

