/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: SF_Proverbial_Gothic25.c                              *
* Font:        SF Proverbial Gothic                                  *
* Height:      25                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  25                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x2D (45)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x2F (47)                                     *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x42 (66)                                     *
* Character enabled:   0x43 (67)                                     *
* Character enabled:   0x44 (68)                                     *
* Character enabled:   0x45 (69)                                     *
* Character enabled:   0x47 (71)                                     *
* Character enabled:   0x46 (70)                                     *
* Character enabled:   0x48 (72)                                     *
* Character enabled:   0x4A (74)                                     *
* Character enabled:   0x49 (73)                                     *
* Character enabled:   0x4B (75)                                     *
* Character enabled:   0x4C (76)                                     *
* Character enabled:   0x4D (77)                                     *
* Character enabled:   0x4E (78)                                     *
* Character enabled:   0x4F (79)                                     *
* Character enabled:   0x50 (80)                                     *
* Character enabled:   0x51 (81)                                     *
* Character enabled:   0x52 (82)                                     *
* Character enabled:   0x53 (83)                                     *
* Character enabled:   0x54 (84)                                     *
* Character enabled:   0x55 (85)                                     *
* Character enabled:   0x56 (86)                                     *
* Character enabled:   0x57 (87)                                     *
* Character enabled:   0x58 (88)                                     *
* Character enabled:   0x59 (89)                                     *
* Character enabled:   0x5A (90)                                     *
* Edit/Cursor Distance/Decrease at character 0x30 (48)               *
* Edit/Cursor Distance/Decrease at character 0x30 (48)               *
* Edit/Move/Left        at character 0x30 (48)                       *
* Edit/Move/Left        at character 0x30 (48)                       *
* Edit/Cursor Distance/Increase at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Cursor Distance/Decrease at character 0x20 (32)               *
* Edit/Move/Left        at character 0x2D (45)                       *
* Edit/Move/Left        at character 0x2E (46)                       *
* Edit/Move/Left        at character 0x2E (46)                       *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Increase at character 0x2F (47)               *
* Edit/Cursor Distance/Increase at character 0x2F (47)               *
* Edit/Cursor Distance/Increase at character 0x31 (49)               *
* Edit/Cursor Distance/Increase at character 0x31 (49)               *
* Edit/Cursor Distance/Increase at character 0x31 (49)               *
* Edit/Cursor Distance/Increase at character 0x31 (49)               *
* Edit/Move/Right       at character 0x31 (49)                       *
* Edit/Cursor Distance/Decrease at character 0x32 (50)               *
* Edit/Move/Left        at character 0x32 (50)                       *
* Edit/Cursor Distance/Decrease at character 0x33 (51)               *
* Edit/Cursor Distance/Decrease at character 0x34 (52)               *
* Edit/Move/Left        at character 0x34 (52)                       *
* Edit/Move/Left        at character 0x35 (53)                       *
* Edit/Cursor Distance/Decrease at character 0x35 (53)               *
* Edit/Move/Left        at character 0x36 (54)                       *
* Edit/Move/Left        at character 0x36 (54)                       *
* Edit/Cursor Distance/Decrease at character 0x36 (54)               *
* Edit/Cursor Distance/Decrease at character 0x36 (54)               *
* Edit/Move/Left        at character 0x37 (55)                       *
* Edit/Move/Left        at character 0x38 (56)                       *
* Edit/Move/Left        at character 0x38 (56)                       *
* Edit/Cursor Distance/Decrease at character 0x38 (56)               *
* Edit/Cursor Distance/Decrease at character 0x38 (56)               *
* Edit/Move/Left        at character 0x39 (57)                       *
* Edit/Move/Left        at character 0x39 (57)                       *
* Edit/Cursor Distance/Decrease at character 0x39 (57)               *
* Edit/Cursor Distance/Decrease at character 0x39 (57)               *
* Edit/Cursor Distance/Increase at character 0x41 (65)               *
* Edit/Cursor Distance/Increase at character 0x41 (65)               *
* Edit/Cursor Distance/Decrease at character 0x41 (65)               *
* Edit/Cursor Distance/Increase at character 0x41 (65)               *
* Edit/Move/Left        at character 0x42 (66)                       *
* Edit/Move/Left        at character 0x43 (67)                       *
* Edit/Cursor Distance/Increase at character 0x43 (67)               *
* Edit/Move/Left        at character 0x44 (68)                       *
* Edit/Move/Left        at character 0x45 (69)                       *
* Edit/Cursor Distance/Increase at character 0x45 (69)               *
* Edit/Move/Left        at character 0x46 (70)                       *
* Edit/Cursor Distance/Increase at character 0x46 (70)               *
* Edit/Move/Left        at character 0x47 (71)                       *
* Edit/Cursor Distance/Increase at character 0x47 (71)               *
* Edit/Move/Left        at character 0x48 (72)                       *
* Edit/Move/Left        at character 0x49 (73)                       *
* Edit/Cursor Distance/Increase at character 0x49 (73)               *
* Edit/Cursor Distance/Increase at character 0x4A (74)               *
* Edit/Cursor Distance/Increase at character 0x4A (74)               *
* Edit/Move/Left        at character 0x4B (75)                       *
* Edit/Cursor Distance/Increase at character 0x4B (75)               *
* Edit/Cursor Distance/Increase at character 0x4B (75)               *
* Edit/Cursor Distance/Decrease at character 0x4B (75)               *
* Edit/Delete/Right     at character 0x4B (75)                       *
* Edit/Cursor Distance/Increase at character 0x4B (75)               *
* Edit/Move/Left        at character 0x4C (76)                       *
* Edit/Cursor Distance/Increase at character 0x4C (76)               *
* Edit/Move/Left        at character 0x4D (77)                       *
* Edit/Move/Left        at character 0x4E (78)                       *
* Edit/Move/Left        at character 0x4F (79)                       *
* Edit/Move/Left        at character 0x50 (80)                       *
* Edit/Cursor Distance/Increase at character 0x50 (80)               *
* Edit/Cursor Distance/Increase at character 0x51 (81)               *
* Edit/Cursor Distance/Increase at character 0x51 (81)               *
* Edit/Move/Left        at character 0x52 (82)                       *
* Edit/Cursor Distance/Increase at character 0x53 (83)               *
* Edit/Cursor Distance/Increase at character 0x53 (83)               *
* Edit/Delete/Right     at character 0x54 (84)                       *
* Edit/Delete/Left      at character 0x54 (84)                       *
* Edit/Move/Right       at character 0x54 (84)                       *
* Edit/Cursor Distance/Increase at character 0x54 (84)               *
* Edit/Cursor Distance/Increase at character 0x54 (84)               *
* Edit/Cursor Distance/Increase at character 0x54 (84)               *
* Edit/Move/Left        at character 0x55 (85)                       *
* Edit/Cursor Distance/Increase at character 0x56 (86)               *
* Edit/Cursor Distance/Increase at character 0x56 (86)               *
* Edit/Cursor Distance/Increase at character 0x57 (87)               *
* Edit/Cursor Distance/Increase at character 0x57 (87)               *
* Edit/Cursor Distance/Increase at character 0x58 (88)               *
* Edit/Cursor Distance/Increase at character 0x58 (88)               *
* Edit/Delete/Right     at character 0x59 (89)                       *
* Edit/Delete/Left      at character 0x59 (89)                       *
* Edit/Move/Right       at character 0x59 (89)                       *
* Edit/Cursor Distance/Increase at character 0x59 (89)               *
* Edit/Cursor Distance/Increase at character 0x59 (89)               *
* Edit/Cursor Distance/Increase at character 0x59 (89)               *
* Edit/Cursor Distance/Increase at character 0x5A (90)               *
* Edit/Cursor Distance/Increase at character 0x5A (90)               *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSF_Proverbial_Gothic25;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_002D[  4] = { /* code 002D, HYPHEN-MINUS */
  0x3F, 0xFD,
  0x3F, 0xFD
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_002E[  2] = { /* code 002E, FULL STOP */
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_002F[ 32] = { /* code 002F, SOLIDUS */
  0x00, 0x0D,
  0x00, 0x2D,
  0x00, 0x3C,
  0x00, 0x7C,
  0x00, 0xB4,
  0x00, 0xF0,
  0x01, 0xE0,
  0x03, 0xD0,
  0x03, 0xC0,
  0x0B, 0x80,
  0x0F, 0x00,
  0x1F, 0x00,
  0x2D, 0x00,
  0x3C, 0x00,
  0x78, 0x00,
  0x74, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0030[ 26] = { /* code 0030, DIGIT ZERO */
  0xBF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xBF, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0031[ 13] = { /* code 0031, DIGIT ONE */
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0032[ 39] = { /* code 0032, DIGIT TWO */
  0xFF, 0xFF, 0x80,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0xBF, 0xFF, 0x80,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xBF, 0xFF, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0033[ 39] = { /* code 0033, DIGIT THREE */
  0x7F, 0xFF, 0x80,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x03, 0xFF, 0x00,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x7F, 0xFF, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0034[ 26] = { /* code 0034, DIGIT FOUR */
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xFF, 0xFF,
  0x00, 0x0F,
  0x00, 0x0F,
  0x00, 0x0F
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0035[ 39] = { /* code 0035, DIGIT FIVE */
  0xBF, 0xFF, 0xC0,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xBF, 0xFF, 0x80,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0xFF, 0xFF, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0036[ 26] = { /* code 0036, DIGIT SIX */
  0xBF, 0xFF,
  0xF0, 0x00,
  0xF0, 0x00,
  0xFF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xBF, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0037[ 39] = { /* code 0037, DIGIT SEVEN */
  0xFF, 0xFF, 0x00,
  0x00, 0x3F, 0x00,
  0x00, 0x3D, 0x00,
  0x00, 0xBC, 0x00,
  0x00, 0xF4, 0x00,
  0x02, 0xF0, 0x00,
  0x03, 0xD0, 0x00,
  0x07, 0xC0, 0x00,
  0x0F, 0x80, 0x00,
  0x1F, 0x00, 0x00,
  0x3E, 0x00, 0x00,
  0x3C, 0x00, 0x00,
  0xB8, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0038[ 26] = { /* code 0038, DIGIT EIGHT */
  0xBF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0x3F, 0xFD,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xBF, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0039[ 26] = { /* code 0039, DIGIT NINE */
  0xBF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xBF, 0xFF,
  0x00, 0x0F,
  0x00, 0x0F,
  0xFF, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0041[ 39] = { /* code 0041, LATIN CAPITAL LETTER A */
  0x03, 0xE0, 0x00,
  0x03, 0xF0, 0x00,
  0x03, 0xF0, 0x00,
  0x07, 0xF4, 0x00,
  0x0A, 0xB8, 0x00,
  0x0D, 0x7C, 0x00,
  0x0C, 0x3C, 0x00,
  0x1C, 0x3D, 0x00,
  0x28, 0x3E, 0x00,
  0x3F, 0xFE, 0x00,
  0x30, 0x0F, 0x00,
  0x70, 0x0F, 0x00,
  0xA0, 0x0B, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0042[ 26] = { /* code 0042, LATIN CAPITAL LETTER B */
  0xFF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xFF, 0xFC,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xFF, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0043[ 26] = { /* code 0043, LATIN CAPITAL LETTER C */
  0xBF, 0xFC,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xBF, 0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0044[ 26] = { /* code 0044, LATIN CAPITAL LETTER D */
  0xFF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xFF, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0045[ 26] = { /* code 0045, LATIN CAPITAL LETTER E */
  0xFF, 0xFC,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xFF, 0xFC,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xFF, 0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0046[ 26] = { /* code 0046, LATIN CAPITAL LETTER F */
  0xFF, 0xFC,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xFF, 0xFC,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0047[ 26] = { /* code 0047, LATIN CAPITAL LETTER G */
  0xBF, 0xFF,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0xFF,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xBF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0048[ 26] = { /* code 0048, LATIN CAPITAL LETTER H */
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xFF, 0xFF,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0049[ 13] = { /* code 0049, LATIN CAPITAL LETTER I */
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_004A[ 26] = { /* code 004A, LATIN CAPITAL LETTER J */
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0xF0, 0x3C,
  0xF0, 0x3C,
  0xBF, 0xF8
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_004B[ 26] = { /* code 004B, LATIN CAPITAL LETTER K */
  0xF0, 0x0F,
  0xF0, 0x2D,
  0xF0, 0x78,
  0xF0, 0xF0,
  0xF2, 0xC0,
  0xF7, 0x80,
  0xFF, 0x00,
  0xFF, 0x80,
  0xFF, 0xC0,
  0xF7, 0xF0,
  0xF2, 0xF8,
  0xF0, 0xFD,
  0xF0, 0x3F
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_004C[ 26] = { /* code 004C, LATIN CAPITAL LETTER L */
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xFF, 0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_004D[ 39] = { /* code 004D, LATIN CAPITAL LETTER M */
  0xFC, 0x00, 0x3F,
  0xFC, 0x00, 0x3F,
  0xFD, 0x00, 0x7F,
  0xFA, 0x00, 0xAF,
  0xF7, 0x00, 0xDF,
  0xF3, 0x41, 0xCF,
  0xF3, 0x82, 0xCF,
  0xF2, 0xC3, 0x8F,
  0xF1, 0xC3, 0x4F,
  0xF0, 0xD7, 0x0F,
  0xF0, 0xEB, 0x0F,
  0xF0, 0xBD, 0x0F,
  0xF0, 0x3C, 0x0F
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_004E[ 26] = { /* code 004E, LATIN CAPITAL LETTER N */
  0xFC, 0x0F,
  0xFC, 0x0F,
  0xFD, 0x0F,
  0xFB, 0x0F,
  0xF7, 0x0F,
  0xF3, 0x4F,
  0xF2, 0x8F,
  0xF1, 0xCF,
  0xF0, 0xDF,
  0xF0, 0xEF,
  0xF0, 0x7F,
  0xF0, 0x3F,
  0xF0, 0x3F
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_004F[ 26] = { /* code 004F, LATIN CAPITAL LETTER O */
  0xBF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xBF, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0050[ 26] = { /* code 0050, LATIN CAPITAL LETTER P */
  0xFF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xFF, 0xFE,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0051[ 48] = { /* code 0051, LATIN CAPITAL LETTER Q */
  0xBF, 0xFF, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xBF, 0xFF, 0x80,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0052[ 26] = { /* code 0052, LATIN CAPITAL LETTER R */
  0xFF, 0xFE,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xFF, 0xFD,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0053[ 39] = { /* code 0053, LATIN CAPITAL LETTER S */
  0xBF, 0xFF, 0xC0,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xBF, 0xFF, 0x80,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0xFF, 0xFF, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0054[ 26] = { /* code 0054, LATIN CAPITAL LETTER T */
  0xFF, 0xFF,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0055[ 26] = { /* code 0055, LATIN CAPITAL LETTER U */
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xF0, 0x0F,
  0xBF, 0xFE
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0056[ 39] = { /* code 0056, LATIN CAPITAL LETTER V */
  0xB8, 0x02, 0x40,
  0x78, 0x03, 0x00,
  0x3C, 0x03, 0x00,
  0x3C, 0x06, 0x00,
  0x2D, 0x0A, 0x00,
  0x1E, 0x0D, 0x00,
  0x0F, 0x0C, 0x00,
  0x0F, 0x1C, 0x00,
  0x0B, 0x68, 0x00,
  0x07, 0xB4, 0x00,
  0x03, 0xF0, 0x00,
  0x03, 0xF0, 0x00,
  0x03, 0xE0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0057[ 52] = { /* code 0057, LATIN CAPITAL LETTER W */
  0x78, 0x03, 0x40, 0x60,
  0x7C, 0x07, 0x40, 0xA0,
  0x3C, 0x07, 0x80, 0xD0,
  0x3D, 0x0B, 0xC0, 0xC0,
  0x2E, 0x0F, 0xC1, 0xC0,
  0x1F, 0x0F, 0xD2, 0x80,
  0x0F, 0x0E, 0xD3, 0x40,
  0x0F, 0x59, 0xE3, 0x00,
  0x0B, 0x64, 0xF7, 0x00,
  0x07, 0xB4, 0xFA, 0x00,
  0x03, 0xF0, 0xFD, 0x00,
  0x03, 0xF0, 0xBC, 0x00,
  0x02, 0xE0, 0x7C, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0058[ 39] = { /* code 0058, LATIN CAPITAL LETTER X */
  0x7C, 0x02, 0x80,
  0x3D, 0x03, 0x00,
  0x1F, 0x0A, 0x00,
  0x0F, 0x4D, 0x00,
  0x0B, 0x9C, 0x00,
  0x03, 0xF4, 0x00,
  0x03, 0xF0, 0x00,
  0x03, 0xF4, 0x00,
  0x0A, 0x7C, 0x00,
  0x0D, 0x3D, 0x00,
  0x1C, 0x2E, 0x00,
  0x34, 0x0F, 0x00,
  0x70, 0x0B, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_0059[ 26] = { /* code 0059, LATIN CAPITAL LETTER Y */
  0xF4, 0x07,
  0x7C, 0x0E,
  0x3C, 0x0C,
  0x2E, 0x28,
  0x0F, 0x30,
  0x0F, 0xF0,
  0x07, 0xD0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontSF_Proverbial_Gothic25_005A[ 39] = { /* code 005A, LATIN CAPITAL LETTER Z */
  0xBF, 0xFF, 0x40,
  0x00, 0x2F, 0x00,
  0x00, 0x3E, 0x00,
  0x00, 0x7C, 0x00,
  0x00, 0xF8, 0x00,
  0x01, 0xF4, 0x00,
  0x03, 0xF0, 0x00,
  0x03, 0xD0, 0x00,
  0x0B, 0xC0, 0x00,
  0x0F, 0x80, 0x00,
  0x2F, 0x00, 0x00,
  0x3E, 0x00, 0x00,
  0x7F, 0xFF, 0x80
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontSF_Proverbial_Gothic25_CharInfo[40] = {
   {   1,   1,   0,  19,   5, acGUI_FontSF_Proverbial_Gothic25_0020 } /* code 0020, SPACE */
  ,{   8,   2,   0,  11,  10, acGUI_FontSF_Proverbial_Gothic25_002D } /* code 002D, HYPHEN-MINUS */
  ,{   2,   2,   0,  17,   4, acGUI_FontSF_Proverbial_Gothic25_002E } /* code 002E, FULL STOP */
  ,{   8,  16,   0,   4,  10, acGUI_FontSF_Proverbial_Gothic25_002F } /* code 002F, SOLIDUS */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0030 } /* code 0030, DIGIT ZERO */
  ,{   2,  13,   3,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0033 } /* code 0033, DIGIT THREE */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0035 } /* code 0035, DIGIT FIVE */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0037 } /* code 0037, DIGIT SEVEN */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0038 } /* code 0038, DIGIT EIGHT */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0039 } /* code 0039, DIGIT NINE */
  ,{   9,  13,   0,   6,  11, acGUI_FontSF_Proverbial_Gothic25_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{   7,  13,   0,   6,   9, acGUI_FontSF_Proverbial_Gothic25_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{   7,  13,   0,   6,   9, acGUI_FontSF_Proverbial_Gothic25_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   7,  13,   0,   6,   9, acGUI_FontSF_Proverbial_Gothic25_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  13,   0,   6,   4, acGUI_FontSF_Proverbial_Gothic25_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   7,  13,   0,   6,   9, acGUI_FontSF_Proverbial_Gothic25_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   7,  13,   0,   6,   9, acGUI_FontSF_Proverbial_Gothic25_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  12,  13,   0,   6,  14, acGUI_FontSF_Proverbial_Gothic25_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{   9,  16,   0,   6,  11, acGUI_FontSF_Proverbial_Gothic25_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{   9,  13,   0,   6,  11, acGUI_FontSF_Proverbial_Gothic25_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{   9,  13,   0,   6,  11, acGUI_FontSF_Proverbial_Gothic25_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  14,  13,   0,   6,  16, acGUI_FontSF_Proverbial_Gothic25_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{   9,  13,   0,   6,  11, acGUI_FontSF_Proverbial_Gothic25_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{   8,  13,   0,   6,  10, acGUI_FontSF_Proverbial_Gothic25_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{   9,  13,   0,   6,  11, acGUI_FontSF_Proverbial_Gothic25_005A } /* code 005A, LATIN CAPITAL LETTER Z */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSF_Proverbial_Gothic25_Prop3 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontSF_Proverbial_Gothic25_CharInfo[ 14] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSF_Proverbial_Gothic25_Prop2 = {
   0x002D /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontSF_Proverbial_Gothic25_CharInfo[  1] /* address of first character */
  ,&GUI_FontSF_Proverbial_Gothic25_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontSF_Proverbial_Gothic25_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontSF_Proverbial_Gothic25_CharInfo[  0] /* address of first character */
  ,&GUI_FontSF_Proverbial_Gothic25_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSF_Proverbial_Gothic25 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,25 /* height of font  */
  ,25 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSF_Proverbial_Gothic25_Prop1}
  ,19 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

