/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: UKIJ_Saet35.c                                         *
* Font:        UKIJ Saet                                             *
* Height:      35                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  35                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x42 (66)                                     *
* Character enabled:   0x59 (89)                                     *
* Character enabled:   0x50 (80)                                     *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x53 (83)                                     *
* Character disabled:  0x53 (83)                                     *
* Character enabled:   0x53 (83)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontUKIJ_Saet35;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontUKIJ_Saet35_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontUKIJ_Saet35_0041[ 72] = { /* code 0041, LATIN CAPITAL LETTER A */
  0x1F, 0xFF, 0xFF, 0xD0,
  0x36, 0xFF, 0xFF, 0x68,
  0x3D, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x39, 0x55, 0x55, 0xB8,
  0x0F, 0xFF, 0xFF, 0xD0,
  0x39, 0xAA, 0xAA, 0x68,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3C, 0x00, 0x00, 0xB8,
  0x20, 0x00, 0x00, 0x18,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontUKIJ_Saet35_0042[ 72] = { /* code 0042, LATIN CAPITAL LETTER B */
  0x1F, 0xFF, 0xFE, 0x00,
  0x36, 0xFF, 0xFF, 0x40,
  0x3D, 0x00, 0x01, 0xF4,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x39, 0x55, 0x55, 0xB8,
  0x0F, 0xFF, 0xFF, 0xD0,
  0x39, 0xAA, 0xAA, 0x68,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x39, 0xFF, 0xFE, 0x50,
  0x1F, 0xFF, 0xFF, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontUKIJ_Saet35_0050[ 72] = { /* code 0050, LATIN CAPITAL LETTER P */
  0x1F, 0xFF, 0xFE, 0x00,
  0x36, 0xFF, 0xFF, 0x40,
  0x3D, 0x00, 0x01, 0xF4,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x39, 0x55, 0x55, 0xB8,
  0x0F, 0xFF, 0xFF, 0xD0,
  0x39, 0xAA, 0xA9, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x3C, 0x00, 0x00, 0x00,
  0x20, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontUKIJ_Saet35_0053[ 72] = { /* code 0053, LATIN CAPITAL LETTER S */
  0x01, 0xFF, 0xFF, 0xE0,
  0x07, 0xFF, 0xFF, 0x40,
  0x3D, 0x00, 0x00, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x3E, 0x00, 0x00, 0x00,
  0x39, 0x55, 0x55, 0x00,
  0x0F, 0xFF, 0xFF, 0xD0,
  0x01, 0xAA, 0xAA, 0x68,
  0x00, 0x00, 0x01, 0xF8,
  0x00, 0x00, 0x01, 0xF8,
  0x00, 0x00, 0x01, 0xF8,
  0x00, 0x00, 0x01, 0xF8,
  0x00, 0x00, 0x01, 0xF8,
  0x02, 0xFF, 0xFE, 0x50,
  0x1F, 0xFF, 0xFF, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontUKIJ_Saet35_0059[ 72] = { /* code 0059, LATIN CAPITAL LETTER Y */
  0x10, 0x00, 0x00, 0x04,
  0x38, 0x00, 0x00, 0x78,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x3E, 0x00, 0x01, 0xF8,
  0x39, 0x55, 0x55, 0xB8,
  0x0F, 0xFF, 0xFF, 0xD0,
  0x01, 0xAA, 0xA9, 0x00,
  0x00, 0x0B, 0xC0, 0x00,
  0x00, 0x0B, 0xC0, 0x00,
  0x00, 0x0B, 0xC0, 0x00,
  0x00, 0x0B, 0xC0, 0x00,
  0x00, 0x0B, 0xC0, 0x00,
  0x00, 0x0B, 0xC0, 0x00,
  0x00, 0x03, 0x40, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontUKIJ_Saet35_CharInfo[6] = {
   {   1,   1,   0,  25,   8, acGUI_FontUKIJ_Saet35_0020 } /* code 0020, SPACE */
  ,{  15,  18,   1,   8,  17, acGUI_FontUKIJ_Saet35_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  15,  18,   1,   8,  17, acGUI_FontUKIJ_Saet35_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  15,  18,   1,   8,  17, acGUI_FontUKIJ_Saet35_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  15,  18,   1,   8,  17, acGUI_FontUKIJ_Saet35_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  15,  18,   1,   8,  17, acGUI_FontUKIJ_Saet35_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontUKIJ_Saet35_Prop5 = {
   0x0059 /* first character */
  ,0x0059 /* last character  */
  ,&GUI_FontUKIJ_Saet35_CharInfo[  5] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontUKIJ_Saet35_Prop4 = {
   0x0053 /* first character */
  ,0x0053 /* last character  */
  ,&GUI_FontUKIJ_Saet35_CharInfo[  4] /* address of first character */
  ,&GUI_FontUKIJ_Saet35_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontUKIJ_Saet35_Prop3 = {
   0x0050 /* first character */
  ,0x0050 /* last character  */
  ,&GUI_FontUKIJ_Saet35_CharInfo[  3] /* address of first character */
  ,&GUI_FontUKIJ_Saet35_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontUKIJ_Saet35_Prop2 = {
   0x0041 /* first character */
  ,0x0042 /* last character  */
  ,&GUI_FontUKIJ_Saet35_CharInfo[  1] /* address of first character */
  ,&GUI_FontUKIJ_Saet35_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontUKIJ_Saet35_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontUKIJ_Saet35_CharInfo[  0] /* address of first character */
  ,&GUI_FontUKIJ_Saet35_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontUKIJ_Saet35 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,35 /* height of font  */
  ,35 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontUKIJ_Saet35_Prop1}
  ,26 /* Baseline */
  ,19 /* Height of lowercase characters */
  ,18 /* Height of capital characters */
};

