/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial22.c                                             *
* Font:        Arial                                                 *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  22                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character disabled:  0x20 (32)                                     *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x3A (58)                                     *
* Character disabled:  0x40 (64)                                     *
* Character disabled:  0x5B (91)                                     *
* Character disabled:  0x5C (92)                                     *
* Character disabled:  0x5D (93)                                     *
* Character disabled:  0x5E (94)                                     *
* Character disabled:  0x5F (95)                                     *
* Pixel index of character 0x26 (38) at 0/11 set to 0                *
* Pixel index of character 0x26 (38) at 1/12 set to 0                *
* Pixel index of character 0x26 (38) at 1/11 set to 0                *
* Pixel index of character 0x26 (38) at 1/10 set to 0                *
* Pixel index of character 0x26 (38) at 1/9 set to 0                 *
* Pixel index of character 0x26 (38) at 1/8 set to 0                 *
* Pixel index of character 0x26 (38) at 1/7 set to 0                 *
* Pixel index of character 0x26 (38) at 1/6 set to 0                 *
* Pixel index of character 0x26 (38) at 1/5 set to 0                 *
* Pixel index of character 0x26 (38) at 1/4 set to 0                 *
* Pixel index of character 0x26 (38) at 1/3 set to 0                 *
* Pixel index of character 0x26 (38) at 1/2 set to 0                 *
* Pixel index of character 0x26 (38) at 1/1 set to 0                 *
* Pixel index of character 0x26 (38) at 1/0 set to 0                 *
* Pixel index of character 0x26 (38) at 2/13 set to 0                *
* Pixel index of character 0x26 (38) at 3/13 set to 0                *
* Pixel index of character 0x26 (38) at 4/13 set to 0                *
* Pixel index of character 0x26 (38) at 5/13 set to 0                *
* Pixel index of character 0x26 (38) at 6/13 set to 0                *
* Pixel index of character 0x26 (38) at 7/13 set to 0                *
* Pixel index of character 0x26 (38) at 8/13 set to 0                *
* Pixel index of character 0x26 (38) at 9/13 set to 0                *
* Pixel index of character 0x26 (38) at 10/13 set to 0               *
* Pixel index of character 0x26 (38) at 11/13 set to 0               *
* Pixel index of character 0x26 (38) at 0/13 set to 0                *
* Pixel index of character 0x26 (38) at 11/12 set to 0               *
* Pixel index of character 0x26 (38) at 10/12 set to 0               *
* Pixel index of character 0x26 (38) at 9/12 set to 0                *
* Pixel index of character 0x26 (38) at 8/12 set to 0                *
* Pixel index of character 0x26 (38) at 7/12 set to 0                *
* Pixel index of character 0x26 (38) at 6/12 set to 0                *
* Pixel index of character 0x26 (38) at 5/12 set to 0                *
* Pixel index of character 0x26 (38) at 4/12 set to 0                *
* Pixel index of character 0x26 (38) at 3/12 set to 0                *
* Pixel index of character 0x26 (38) at 2/12 set to 0                *
* Pixel index of character 0x26 (38) at 2/11 set to 0                *
* Pixel index of character 0x26 (38) at 3/11 set to 0                *
* Pixel index of character 0x26 (38) at 4/11 set to 0                *
* Pixel index of character 0x26 (38) at 5/11 set to 0                *
* Pixel index of character 0x26 (38) at 6/11 set to 0                *
* Pixel index of character 0x26 (38) at 7/11 set to 0                *
* Pixel index of character 0x26 (38) at 8/11 set to 0                *
* Pixel index of character 0x26 (38) at 9/11 set to 0                *
* Pixel index of character 0x26 (38) at 10/10 set to 0               *
* Pixel index of character 0x26 (38) at 9/10 set to 0                *
* Pixel index of character 0x26 (38) at 8/10 set to 0                *
* Pixel index of character 0x26 (38) at 7/10 set to 0                *
* Pixel index of character 0x26 (38) at 6/10 set to 0                *
* Pixel index of character 0x26 (38) at 6/9 set to 0                 *
* Pixel index of character 0x26 (38) at 7/9 set to 0                 *
* Pixel index of character 0x26 (38) at 8/9 set to 0                 *
* Pixel index of character 0x26 (38) at 9/9 set to 0                 *
* Pixel index of character 0x26 (38) at 10/9 set to 0                *
* Pixel index of character 0x26 (38) at 10/9 set to 0                *
* Pixel index of character 0x26 (38) at 9/9 set to 0                 *
* Pixel index of character 0x26 (38) at 8/9 set to 0                 *
* Pixel index of character 0x26 (38) at 7/9 set to 0                 *
* Pixel index of character 0x26 (38) at 6/9 set to 0                 *
* Pixel index of character 0x26 (38) at 5/9 set to 0                 *
* Pixel index of character 0x26 (38) at 4/9 set to 0                 *
* Pixel index of character 0x26 (38) at 3/9 set to 0                 *
* Pixel index of character 0x26 (38) at 2/8 set to 0                 *
* Pixel index of character 0x26 (38) at 3/8 set to 0                 *
* Pixel index of character 0x26 (38) at 4/8 set to 0                 *
* Pixel index of character 0x26 (38) at 5/8 set to 0                 *
* Pixel index of character 0x26 (38) at 6/8 set to 0                 *
* Pixel index of character 0x26 (38) at 7/8 set to 0                 *
* Pixel index of character 0x26 (38) at 8/8 set to 0                 *
* Pixel index of character 0x26 (38) at 9/8 set to 0                 *
* Pixel index of character 0x26 (38) at 10/8 set to 0                *
* Pixel index of character 0x26 (38) at 6/7 set to 0                 *
* Pixel index of character 0x26 (38) at 5/7 set to 0                 *
* Pixel index of character 0x26 (38) at 4/7 set to 0                 *
* Pixel index of character 0x26 (38) at 3/7 set to 0                 *
* Pixel index of character 0x26 (38) at 2/7 set to 0                 *
* Pixel index of character 0x26 (38) at 2/6 set to 0                 *
* Pixel index of character 0x26 (38) at 3/6 set to 0                 *
* Pixel index of character 0x26 (38) at 4/6 set to 0                 *
* Pixel index of character 0x26 (38) at 5/6 set to 0                 *
* Pixel index of character 0x26 (38) at 6/6 set to 0                 *
* Pixel index of character 0x26 (38) at 6/5 set to 0                 *
* Pixel index of character 0x26 (38) at 5/5 set to 0                 *
* Pixel index of character 0x26 (38) at 4/5 set to 0                 *
* Pixel index of character 0x26 (38) at 3/5 set to 0                 *
* Pixel index of character 0x26 (38) at 2/5 set to 0                 *
* Pixel index of character 0x26 (38) at 2/4 set to 0                 *
* Pixel index of character 0x26 (38) at 3/4 set to 0                 *
* Pixel index of character 0x26 (38) at 4/4 set to 0                 *
* Pixel index of character 0x26 (38) at 5/4 set to 0                 *
* Pixel index of character 0x26 (38) at 6/4 set to 0                 *
* Pixel index of character 0x26 (38) at 7/4 set to 0                 *
* Pixel index of character 0x26 (38) at 8/3 set to 0                 *
* Pixel index of character 0x26 (38) at 7/3 set to 0                 *
* Pixel index of character 0x26 (38) at 6/3 set to 0                 *
* Pixel index of character 0x26 (38) at 5/3 set to 0                 *
* Pixel index of character 0x26 (38) at 4/3 set to 0                 *
* Pixel index of character 0x26 (38) at 3/3 set to 0                 *
* Pixel index of character 0x26 (38) at 2/3 set to 0                 *
* Pixel index of character 0x26 (38) at 1/2 set to 0                 *
* Pixel index of character 0x26 (38) at 2/2 set to 0                 *
* Pixel index of character 0x26 (38) at 3/2 set to 0                 *
* Pixel index of character 0x26 (38) at 4/2 set to 0                 *
* Pixel index of character 0x26 (38) at 5/2 set to 0                 *
* Pixel index of character 0x26 (38) at 7/2 set to 0                 *
* Pixel index of character 0x26 (38) at 8/2 set to 0                 *
* Pixel index of character 0x26 (38) at 6/2 set to 0                 *
* Pixel index of character 0x26 (38) at 9/1 set to 0                 *
* Pixel index of character 0x26 (38) at 7/1 set to 0                 *
* Pixel index of character 0x26 (38) at 6/1 set to 0                 *
* Pixel index of character 0x26 (38) at 5/1 set to 0                 *
* Pixel index of character 0x26 (38) at 4/1 set to 0                 *
* Pixel index of character 0x26 (38) at 3/1 set to 0                 *
* Pixel index of character 0x26 (38) at 2/1 set to 0                 *
* Pixel index of character 0x26 (38) at 2/0 set to 0                 *
* Pixel index of character 0x26 (38) at 3/0 set to 0                 *
* Pixel index of character 0x26 (38) at 4/0 set to 0                 *
* Pixel index of character 0x26 (38) at 5/0 set to 0                 *
* Pixel index of character 0x26 (38) at 6/0 set to 0                 *
* Pixel index of character 0x26 (38) at 0/13 set to 3                *
* Pixel index of character 0x26 (38) at 1/13 set to 3                *
* Pixel index of character 0x26 (38) at 2/13 set to 3                *
* Pixel index of character 0x26 (38) at 0/12 set to 3                *
* Pixel index of character 0x26 (38) at 1/12 set to 3                *
* Pixel index of character 0x26 (38) at 2/12 set to 3                *
* Pixel index of character 0x26 (38) at 11/12 set to 3               *
* Pixel index of character 0x26 (38) at 10/12 set to 3               *
* Pixel index of character 0x26 (38) at 9/12 set to 3                *
* Pixel index of character 0x26 (38) at 9/13 set to 3                *
* Pixel index of character 0x26 (38) at 10/13 set to 3               *
* Pixel index of character 0x26 (38) at 11/13 set to 3               *
* Pixel index of character 0x26 (38) at 8/13 set to 3                *
* Pixel index of character 0x26 (38) at 8/12 set to 3                *
* Pixel index of character 0x26 (38) at 7/12 set to 3                *
* Pixel index of character 0x26 (38) at 7/13 set to 3                *
* Pixel index of character 0x26 (38) at 3/13 set to 3                *
* Pixel index of character 0x26 (38) at 3/12 set to 3                *
* Pixel index of character 0x26 (38) at 3/11 set to 3                *
* Pixel index of character 0x26 (38) at 2/10 set to 3                *
* Pixel index of character 0x26 (38) at 1/9 set to 3                 *
* Pixel index of character 0x26 (38) at 0/8 set to 3                 *
* Pixel index of character 0x26 (38) at 0/7 set to 3                 *
* Pixel index of character 0x26 (38) at 0/6 set to 3                 *
* Pixel index of character 0x26 (38) at 0/5 set to 3                 *
* Pixel index of character 0x26 (38) at 0/4 set to 3                 *
* Pixel index of character 0x26 (38) at 1/3 set to 3                 *
* Pixel index of character 0x26 (38) at 2/2 set to 3                 *
* Pixel index of character 0x26 (38) at 3/1 set to 3                 *
* Pixel index of character 0x26 (38) at 4/0 set to 3                 *
* Pixel index of character 0x26 (38) at 5/0 set to 3                 *
* Pixel index of character 0x26 (38) at 6/0 set to 3                 *
* Pixel index of character 0x26 (38) at 7/0 set to 3                 *
* Pixel index of character 0x26 (38) at 8/1 set to 3                 *
* Pixel index of character 0x26 (38) at 9/2 set to 3                 *
* Pixel index of character 0x26 (38) at 10/3 set to 3                *
* Pixel index of character 0x26 (38) at 11/4 set to 3                *
* Pixel index of character 0x26 (38) at 11/5 set to 3                *
* Pixel index of character 0x26 (38) at 11/6 set to 3                *
* Pixel index of character 0x26 (38) at 11/7 set to 3                *
* Pixel index of character 0x26 (38) at 11/8 set to 3                *
* Pixel index of character 0x26 (38) at 10/9 set to 3                *
* Pixel index of character 0x26 (38) at 9/10 set to 3                *
* Pixel index of character 0x26 (38) at 8/11 set to 3                *
* Pixel index of character 0x26 (38) at 7/11 set to 3                *
* Pixel index of character 0x26 (38) at 8/10 set to 3                *
* Pixel index of character 0x26 (38) at 9/9 set to 3                 *
* Pixel index of character 0x26 (38) at 10/8 set to 3                *
* Pixel index of character 0x26 (38) at 10/9 set to 0                *
* Pixel index of character 0x26 (38) at 9/10 set to 0                *
* Pixel index of character 0x26 (38) at 8/11 set to 0                *
* Pixel index of character 0x26 (38) at 7/13 set to 0                *
* Pixel index of character 0x26 (38) at 7/12 set to 0                *
* Pixel index of character 0x26 (38) at 7/11 set to 0                *
* Pixel index of character 0x26 (38) at 8/11 set to 3                *
* Pixel index of character 0x26 (38) at 9/10 set to 3                *
* Pixel index of character 0x26 (38) at 10/9 set to 3                *
* Pixel index of character 0x26 (38) at 11/8 set to 3                *
* Pixel index of character 0x26 (38) at 10/8 set to 0                *
* Pixel index of character 0x26 (38) at 9/9 set to 0                 *
* Pixel index of character 0x26 (38) at 8/10 set to 0                *
* Pixel index of character 0x26 (38) at 2/1 set to 3                 *
* Pixel index of character 0x26 (38) at 1/2 set to 3                 *
* Pixel index of character 0x26 (38) at 2/2 set to 0                 *
* Pixel index of character 0x26 (38) at 3/1 set to 0                 *
* Pixel index of character 0x26 (38) at 3/0 set to 3                 *
* Pixel index of character 0x26 (38) at 8/0 set to 3                 *
* Pixel index of character 0x26 (38) at 9/1 set to 3                 *
* Pixel index of character 0x26 (38) at 8/1 set to 0                 *
* Pixel index of character 0x26 (38) at 10/2 set to 3                *
* Pixel index of character 0x26 (38) at 9/2 set to 0                 *
* Pixel index of character 0x26 (38) at 10/8 set to 3                *
* Pixel index of character 0x26 (38) at 10/7 set to 3                *
* Pixel index of character 0x26 (38) at 10/6 set to 3                *
* Pixel index of character 0x26 (38) at 10/5 set to 3                *
* Pixel index of character 0x26 (38) at 10/4 set to 3                *
* Pixel index of character 0x26 (38) at 1/4 set to 3                 *
* Pixel index of character 0x26 (38) at 1/5 set to 3                 *
* Pixel index of character 0x26 (38) at 1/6 set to 3                 *
* Pixel index of character 0x26 (38) at 1/7 set to 3                 *
* Pixel index of character 0x26 (38) at 1/8 set to 3                 *
* Pixel index of character 0x26 (38) at 3/10 set to 2                *
* Pixel index of character 0x26 (38) at 2/9 set to 2                 *
* Pixel index of character 0x26 (38) at 2/11 set to 0                *
* Pixel index of character 0x26 (38) at 2/11 set to 1                *
* Pixel index of character 0x26 (38) at 1/10 set to 1                *
* Pixel index of character 0x26 (38) at 0/9 set to 1                 *
* Pixel index of character 0x26 (38) at 0/3 set to 2                 *
* Pixel index of character 0x26 (38) at 0/2 set to 1                 *
* Pixel index of character 0x26 (38) at 1/1 set to 1                 *
* Pixel index of character 0x26 (38) at 2/0 set to 1                 *
* Pixel index of character 0x26 (38) at 2/2 set to 2                 *
* Pixel index of character 0x26 (38) at 3/1 set to 2                 *
* Pixel index of character 0x26 (38) at 2/3 set to 1                 *
* Pixel index of character 0x26 (38) at 8/1 set to 2                 *
* Pixel index of character 0x26 (38) at 9/2 set to 2                 *
* Pixel index of character 0x26 (38) at 9/3 set to 1                 *
* Pixel index of character 0x26 (38) at 9/0 set to 1                 *
* Pixel index of character 0x26 (38) at 10/1 set to 1                *
* Pixel index of character 0x26 (38) at 11/3 set to 1                *
* Pixel index of character 0x26 (38) at 7/1 set to 2                 *
* Pixel index of character 0x26 (38) at 5/1 set to 2                 *
* Pixel index of character 0x26 (38) at 5/1 set to 2                 *
* Pixel index of character 0x26 (38) at 5/1 set to 2                 *
* Pixel index of character 0x26 (38) at 4/1 set to 2                 *
* Pixel index of character 0x26 (38) at 6/1 set to 2                 *
* Pixel index of character 0x26 (38) at 4/1 set to 1                 *
* Pixel index of character 0x26 (38) at 4/1 set to 2                 *
* Pixel index of character 0x26 (38) at 3/2 set to 1                 *
* Pixel index of character 0x26 (38) at 8/2 set to 1                 *
* Pixel index of character 0x26 (38) at 9/9 set to 2                 *
* Pixel index of character 0x26 (38) at 8/10 set to 2                *
* Pixel index of character 0x26 (38) at 9/11 set to 1                *
* Pixel index of character 0x26 (38) at 10/10 set to 1               *
* Pixel index of character 0x26 (38) at 11/9 set to 1                *
* Pixel index of character 0x26 (38) at 0/3 set to 3                 *
* Pixel index of character 0x26 (38) at 1/1 set to 3                 *
* Pixel index of character 0x26 (38) at 2/0 set to 3                 *
* Pixel index of character 0x26 (38) at 1/1 set to 2                 *
* Pixel index of character 0x26 (38) at 2/0 set to 1                 *
* Pixel index of character 0x26 (38) at 1/1 set to 2                 *
* Pixel index of character 0x26 (38) at 1/1 set to 1                 *
* Pixel index of character 0x26 (38) at 2/2 set to 3                 *
* Pixel index of character 0x26 (38) at 0/3 set to 1                 *
* Pixel index of character 0x26 (38) at 0/3 set to 2                 *
* Pixel index of character 0x26 (38) at 3/1 set to 2                 *
* Pixel index of character 0x26 (38) at 3/1 set to 3                 *
* Pixel index of character 0x26 (38) at 8/1 set to 2                 *
* Pixel index of character 0x26 (38) at 8/1 set to 3                 *
* Pixel index of character 0x26 (38) at 9/2 set to 2                 *
* Pixel index of character 0x26 (38) at 9/2 set to 3                 *
* Pixel index of character 0x26 (38) at 11/3 set to 2                *
* Pixel index of character 0x26 (38) at 11/2 set to 1                *
* Pixel index of character 0x26 (38) at 9/3 set to 2                 *
* Pixel index of character 0x26 (38) at 2/3 set to 2                 *
* Pixel index of character 0x26 (38) at 4/11 set to 2                *
* Pixel index of character 0x26 (38) at 4/12 set to 2                *
* Pixel index of character 0x26 (38) at 4/13 set to 2                *
* Pixel index of character 0x26 (38) at 7/11 set to 2                *
* Pixel index of character 0x26 (38) at 7/12 set to 2                *
* Pixel index of character 0x26 (38) at 7/13 set to 2                *
* Character enabled:   0x26 (38)                                     *
* Character enabled:   0x77 (119)                                    *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial22;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0026[ 42] = { /* code 0026, AMPERSAND */
  0x07, 0xFF, 0xD0,
  0x1F, 0xAA, 0xF4,
  0x7D, 0x00, 0x7D,
  0xB8, 0x00, 0x2E,
  0xF0, 0x00, 0x0F,
  0xF0, 0x00, 0x0F,
  0xF0, 0x00, 0x0F,
  0xF0, 0x00, 0x0F,
  0xF0, 0x00, 0x0F,
  0x78, 0x00, 0x2D,
  0x1E, 0x00, 0xB4,
  0x07, 0x82, 0xD0,
  0xFF, 0x82, 0xFF,
  0xFF, 0x82, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_002E[  2] = { /* code 002E, FULL STOP */
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0030[ 42] = { /* code 0030, DIGIT ZERO */
  0x0B, 0xF8, 0x00,
  0x3F, 0xFF, 0x00,
  0x7C, 0x0F, 0x40,
  0xB4, 0x07, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xB4, 0x07, 0x80,
  0x7C, 0x0F, 0x40,
  0x3F, 0xFF, 0x00,
  0x0B, 0xF8, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0031[ 28] = { /* code 0031, DIGIT ONE */
  0x02, 0xC0,
  0x07, 0xC0,
  0x1F, 0xC0,
  0xFB, 0xC0,
  0xE3, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0,
  0x03, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0032[ 42] = { /* code 0032, DIGIT TWO */
  0x0B, 0xF8, 0x00,
  0x3F, 0xFF, 0x00,
  0xB8, 0x0F, 0x80,
  0xF0, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x07, 0x80,
  0x00, 0x0F, 0x00,
  0x00, 0x3D, 0x00,
  0x00, 0xF4, 0x00,
  0x03, 0xD0, 0x00,
  0x1F, 0x00, 0x00,
  0x3C, 0x00, 0x00,
  0xBF, 0xFF, 0xC0,
  0xFF, 0xFF, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0033[ 42] = { /* code 0033, DIGIT THREE */
  0x0B, 0xF4, 0x00,
  0x3F, 0xFD, 0x00,
  0xB8, 0x1F, 0x00,
  0xF0, 0x0F, 0x00,
  0x00, 0x2E, 0x00,
  0x02, 0xF8, 0x00,
  0x02, 0xFE, 0x00,
  0x00, 0x0B, 0x80,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xB8, 0x0B, 0x40,
  0x3F, 0xFF, 0x00,
  0x0B, 0xF4, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0034[ 42] = { /* code 0034, DIGIT FOUR */
  0x00, 0x07, 0x00,
  0x00, 0x0F, 0x00,
  0x00, 0x3F, 0x00,
  0x00, 0xBF, 0x00,
  0x01, 0xDF, 0x00,
  0x07, 0x8F, 0x00,
  0x0F, 0x0F, 0x00,
  0x3C, 0x0F, 0x00,
  0xB4, 0x0F, 0x00,
  0xFF, 0xFF, 0xF0,
  0xFF, 0xFF, 0xF0,
  0x00, 0x0F, 0x00,
  0x00, 0x0F, 0x00,
  0x00, 0x0F, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0035[ 42] = { /* code 0035, DIGIT FIVE */
  0x3F, 0xFF, 0x00,
  0x3F, 0xFF, 0x00,
  0x78, 0x00, 0x00,
  0x78, 0x00, 0x00,
  0xB4, 0x00, 0x00,
  0xB6, 0xF8, 0x00,
  0xFF, 0xFF, 0x00,
  0xF4, 0x0B, 0x80,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xB8, 0x0B, 0x40,
  0x3F, 0xFF, 0x00,
  0x0B, 0xF8, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0036[ 42] = { /* code 0036, DIGIT SIX */
  0x07, 0xF8, 0x00,
  0x1F, 0xFF, 0x00,
  0x3C, 0x0B, 0x80,
  0x78, 0x03, 0xC0,
  0xF0, 0x00, 0x00,
  0xF2, 0xF8, 0x00,
  0xFB, 0xFF, 0x00,
  0xFC, 0x0B, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xB4, 0x03, 0xC0,
  0x7C, 0x0B, 0x80,
  0x2F, 0xFF, 0x00,
  0x07, 0xF8, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0037[ 42] = { /* code 0037, DIGIT SEVEN */
  0xFF, 0xFF, 0xC0,
  0xFF, 0xFF, 0xC0,
  0x00, 0x07, 0x40,
  0x00, 0x0E, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0x74, 0x00,
  0x00, 0xF0, 0x00,
  0x01, 0xE0, 0x00,
  0x03, 0xC0, 0x00,
  0x03, 0xC0, 0x00,
  0x07, 0x80, 0x00,
  0x0B, 0x40, 0x00,
  0x0F, 0x00, 0x00,
  0x0F, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0038[ 42] = { /* code 0038, DIGIT EIGHT */
  0x0B, 0xF8, 0x00,
  0x3F, 0xFF, 0x00,
  0xB8, 0x0B, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xB8, 0x0B, 0x80,
  0x2F, 0xFE, 0x00,
  0x2F, 0xFE, 0x00,
  0xB8, 0x0B, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xB8, 0x0B, 0x80,
  0x3F, 0xFF, 0x00,
  0x0B, 0xF8, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0039[ 42] = { /* code 0039, DIGIT NINE */
  0x0B, 0xF4, 0x00,
  0x3F, 0xFE, 0x00,
  0xB8, 0x0B, 0x40,
  0xF0, 0x03, 0x80,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xB8, 0x0F, 0xC0,
  0x3F, 0xFB, 0xC0,
  0x0B, 0xE3, 0xC0,
  0x00, 0x03, 0xC0,
  0xF0, 0x07, 0x80,
  0xB8, 0x1F, 0x40,
  0x3F, 0xFE, 0x00,
  0x0B, 0xF4, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_003A[ 10] = { /* code 003A, COLON */
  0xF0,
  0xF0,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0x00,
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0041[ 56] = { /* code 0041, LATIN CAPITAL LETTER A */
  0x00, 0x0F, 0xC0, 0x00,
  0x00, 0x1F, 0xD0, 0x00,
  0x00, 0x2E, 0xE0, 0x00,
  0x00, 0x3C, 0xF0, 0x00,
  0x00, 0x78, 0xB4, 0x00,
  0x00, 0xF0, 0x3C, 0x00,
  0x00, 0xF0, 0x3C, 0x00,
  0x02, 0xD0, 0x1E, 0x00,
  0x03, 0xFF, 0xFF, 0x00,
  0x07, 0xFF, 0xFF, 0x40,
  0x0F, 0x40, 0x07, 0xC0,
  0x0F, 0x00, 0x03, 0xC0,
  0x2D, 0x00, 0x01, 0xE0,
  0x3C, 0x00, 0x00, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0042[ 42] = { /* code 0042, LATIN CAPITAL LETTER B */
  0xFF, 0xFD, 0x00,
  0xFF, 0xFF, 0x40,
  0xF0, 0x0B, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x03, 0xC0,
  0xF0, 0x0B, 0x80,
  0xFF, 0xFE, 0x00,
  0xFF, 0xFF, 0x40,
  0xF0, 0x07, 0xD0,
  0xF0, 0x00, 0xF0,
  0xF0, 0x00, 0xF0,
  0xF0, 0x02, 0xF0,
  0xFF, 0xFF, 0xC0,
  0xFF, 0xFE, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0043[ 56] = { /* code 0043, LATIN CAPITAL LETTER C */
  0x01, 0xBF, 0x40, 0x00,
  0x0B, 0xFF, 0xF4, 0x00,
  0x2F, 0x40, 0x7C, 0x00,
  0x7C, 0x00, 0x1E, 0x00,
  0xB4, 0x00, 0x05, 0x00,
  0xF0, 0x00, 0x00, 0x00,
  0xF0, 0x00, 0x00, 0x00,
  0xF0, 0x00, 0x00, 0x00,
  0xF0, 0x00, 0x00, 0x00,
  0xB4, 0x00, 0x0F, 0x00,
  0x7C, 0x00, 0x2D, 0x00,
  0x3F, 0x40, 0xB8, 0x00,
  0x0F, 0xFF, 0xE0, 0x00,
  0x01, 0xFE, 0x40, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0044[ 42] = { /* code 0044, LATIN CAPITAL LETTER D */
  0xFF, 0xFE, 0x00,
  0xFF, 0xFF, 0xC0,
  0xF0, 0x02, 0xF0,
  0xF0, 0x00, 0xF4,
  0xF0, 0x00, 0x78,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x78,
  0xF0, 0x00, 0xF4,
  0xF0, 0x02, 0xF0,
  0xFF, 0xFF, 0xC0,
  0xFF, 0xFE, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0045[ 42] = { /* code 0045, LATIN CAPITAL LETTER E */
  0xFF, 0xFF, 0xF0,
  0xFF, 0xFF, 0xF0,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xFF, 0xFF, 0xC0,
  0xFF, 0xFF, 0xC0,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xFF, 0xFF, 0xF0,
  0xFF, 0xFF, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0046[ 42] = { /* code 0046, LATIN CAPITAL LETTER F */
  0xFF, 0xFF, 0xC0,
  0xFF, 0xFF, 0xC0,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xFF, 0xFF, 0x00,
  0xFF, 0xFF, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0047[ 56] = { /* code 0047, LATIN CAPITAL LETTER G */
  0x00, 0xBF, 0xE0, 0x00,
  0x0B, 0xFF, 0xFD, 0x00,
  0x2F, 0x40, 0x2F, 0x00,
  0x3C, 0x00, 0x0B, 0x80,
  0xB8, 0x00, 0x02, 0x40,
  0xF0, 0x00, 0x00, 0x00,
  0xF0, 0x00, 0x00, 0x00,
  0xF0, 0x03, 0xFF, 0xC0,
  0xF0, 0x03, 0xFF, 0xC0,
  0xB4, 0x00, 0x03, 0xC0,
  0x3C, 0x00, 0x03, 0xC0,
  0x2F, 0x80, 0x1F, 0xC0,
  0x0B, 0xFF, 0xFF, 0x40,
  0x00, 0xBF, 0xE4, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0048[ 42] = { /* code 0048, LATIN CAPITAL LETTER H */
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xFF, 0xFF, 0xFC,
  0xFF, 0xFF, 0xFC,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0049[ 14] = { /* code 0049, LATIN CAPITAL LETTER I */
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_004A[ 28] = { /* code 004A, LATIN CAPITAL LETTER J */
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0x00, 0x3C,
  0xF0, 0x3C,
  0xF4, 0xBC,
  0xBF, 0xF4,
  0x2F, 0xD0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_004B[ 42] = { /* code 004B, LATIN CAPITAL LETTER K */
  0xF0, 0x03, 0xE0,
  0xF0, 0x0F, 0x80,
  0xF0, 0x3F, 0x00,
  0xF0, 0xBC, 0x00,
  0xF2, 0xF0, 0x00,
  0xF7, 0xC0, 0x00,
  0xFF, 0xC0, 0x00,
  0xFF, 0xF0, 0x00,
  0xF4, 0xF8, 0x00,
  0xF0, 0x7D, 0x00,
  0xF0, 0x1F, 0x40,
  0xF0, 0x0B, 0xC0,
  0xF0, 0x02, 0xF0,
  0xF0, 0x00, 0xF8
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_004C[ 28] = { /* code 004C, LATIN CAPITAL LETTER L */
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xF0, 0x00,
  0xFF, 0xFF,
  0xFF, 0xFF
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_004D[ 56] = { /* code 004D, LATIN CAPITAL LETTER M */
  0xE8, 0x00, 0x0A, 0xC0,
  0xFE, 0x00, 0x2F, 0xC0,
  0xFF, 0x00, 0x3F, 0xC0,
  0xFB, 0x00, 0x3B, 0xC0,
  0xF7, 0x80, 0xB7, 0xC0,
  0xF3, 0xC0, 0xF3, 0xC0,
  0xF3, 0xC0, 0xF3, 0xC0,
  0xF2, 0xD1, 0xE3, 0xC0,
  0xF0, 0xE2, 0xD3, 0xC0,
  0xF0, 0xF3, 0xC3, 0xC0,
  0xF0, 0xB7, 0x83, 0xC0,
  0xF0, 0x7F, 0x43, 0xC0,
  0xF0, 0x3F, 0x03, 0xC0,
  0xF0, 0x3F, 0x03, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_004E[ 42] = { /* code 004E, LATIN CAPITAL LETTER N */
  0xF4, 0x00, 0x3C,
  0xFC, 0x00, 0x3C,
  0xFE, 0x00, 0x3C,
  0xFB, 0x40, 0x3C,
  0xF3, 0xC0, 0x3C,
  0xF1, 0xE0, 0x3C,
  0xF0, 0xF0, 0x3C,
  0xF0, 0x3C, 0x3C,
  0xF0, 0x2D, 0x3C,
  0xF0, 0x0F, 0x3C,
  0xF0, 0x07, 0xBC,
  0xF0, 0x02, 0xFC,
  0xF0, 0x00, 0xFC,
  0xF0, 0x00, 0x7C
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_004F[ 56] = { /* code 004F, LATIN CAPITAL LETTER O */
  0x01, 0xBF, 0x90, 0x00,
  0x0B, 0xFF, 0xF8, 0x00,
  0x2F, 0x40, 0x7E, 0x00,
  0x3C, 0x00, 0x0F, 0x00,
  0xB4, 0x00, 0x07, 0x80,
  0xF0, 0x00, 0x03, 0xC0,
  0xF0, 0x00, 0x03, 0xC0,
  0xF0, 0x00, 0x03, 0xC0,
  0xF0, 0x00, 0x03, 0xC0,
  0xB4, 0x00, 0x07, 0x80,
  0x3C, 0x00, 0x0F, 0x00,
  0x2F, 0x40, 0x7E, 0x00,
  0x0B, 0xFF, 0xF8, 0x00,
  0x01, 0xBF, 0x90, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0050[ 42] = { /* code 0050, LATIN CAPITAL LETTER P */
  0xFF, 0xFE, 0x00,
  0xFF, 0xFF, 0xC0,
  0xF0, 0x02, 0xE0,
  0xF0, 0x00, 0xF0,
  0xF0, 0x00, 0xF0,
  0xF0, 0x00, 0xF0,
  0xF0, 0x03, 0xE0,
  0xFF, 0xFF, 0xC0,
  0xFF, 0xFE, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00,
  0xF0, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0051[ 60] = { /* code 0051, LATIN CAPITAL LETTER Q */
  0x01, 0xBF, 0x90, 0x00,
  0x0B, 0xFF, 0xF8, 0x00,
  0x2F, 0x40, 0x7E, 0x00,
  0x3C, 0x00, 0x0F, 0x40,
  0xB4, 0x00, 0x07, 0x80,
  0xF0, 0x00, 0x03, 0xC0,
  0xF0, 0x00, 0x03, 0xC0,
  0xF0, 0x00, 0x03, 0xC0,
  0xF0, 0x00, 0x03, 0xC0,
  0xB4, 0x00, 0x07, 0x40,
  0x3C, 0x07, 0x9F, 0x00,
  0x2F, 0x41, 0xFD, 0x00,
  0x0B, 0xFF, 0xFC, 0x00,
  0x01, 0xBF, 0x9B, 0x80,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0052[ 42] = { /* code 0052, LATIN CAPITAL LETTER R */
  0xFF, 0xFF, 0x40,
  0xFF, 0xFF, 0xD0,
  0xF0, 0x02, 0xF0,
  0xF0, 0x00, 0xF0,
  0xF0, 0x00, 0xF0,
  0xF0, 0x02, 0xF0,
  0xFF, 0xFF, 0xD0,
  0xFF, 0xFF, 0x40,
  0xF0, 0x3D, 0x00,
  0xF0, 0x0F, 0x40,
  0xF0, 0x0B, 0xC0,
  0xF0, 0x03, 0xE0,
  0xF0, 0x00, 0xF0,
  0xF0, 0x00, 0xB8
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0053[ 42] = { /* code 0053, LATIN CAPITAL LETTER S */
  0x02, 0xFF, 0x80,
  0x0F, 0xFF, 0xF0,
  0x2E, 0x00, 0xF8,
  0x3C, 0x00, 0x3C,
  0x3C, 0x00, 0x00,
  0x1F, 0x80, 0x00,
  0x07, 0xFE, 0x40,
  0x00, 0x1B, 0xF0,
  0x00, 0x00, 0x78,
  0xF0, 0x00, 0x3C,
  0xF4, 0x00, 0x3C,
  0x7E, 0x01, 0xF8,
  0x2F, 0xFF, 0xF0,
  0x06, 0xFF, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0054[ 42] = { /* code 0054, LATIN CAPITAL LETTER T */
  0xFF, 0xFF, 0xF0,
  0xFF, 0xFF, 0xF0,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00,
  0x00, 0xF0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0055[ 42] = { /* code 0055, LATIN CAPITAL LETTER U */
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xB4, 0x00, 0x78,
  0x7D, 0x01, 0xF4,
  0x2F, 0xFF, 0xE0,
  0x07, 0xFE, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0056[ 56] = { /* code 0056, LATIN CAPITAL LETTER V */
  0x3C, 0x00, 0x00, 0xF0,
  0x3D, 0x00, 0x01, 0xF0,
  0x1E, 0x00, 0x02, 0xD0,
  0x0F, 0x00, 0x03, 0xC0,
  0x0B, 0x40, 0x07, 0x80,
  0x03, 0xC0, 0x0F, 0x00,
  0x03, 0xC0, 0x0F, 0x00,
  0x01, 0xE0, 0x2D, 0x00,
  0x00, 0xF0, 0x3C, 0x00,
  0x00, 0xB4, 0x78, 0x00,
  0x00, 0x3C, 0xF0, 0x00,
  0x00, 0x2D, 0xE0, 0x00,
  0x00, 0x1F, 0xD0, 0x00,
  0x00, 0x0F, 0xC0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0057[ 70] = { /* code 0057, LATIN CAPITAL LETTER W */
  0xF0, 0x00, 0xFC, 0x00, 0x3C,
  0xB4, 0x01, 0xFD, 0x00, 0x78,
  0x78, 0x02, 0xEE, 0x00, 0xB4,
  0x78, 0x03, 0xCF, 0x00, 0xB4,
  0x3C, 0x07, 0x8B, 0x40, 0xF0,
  0x3C, 0x0B, 0x47, 0x80, 0xF0,
  0x2D, 0x0F, 0x03, 0xC1, 0xE0,
  0x1E, 0x0F, 0x03, 0xC2, 0xD0,
  0x0F, 0x1E, 0x02, 0xD3, 0xD0,
  0x0F, 0x3C, 0x00, 0xE3, 0xC0,
  0x0F, 0x3C, 0x00, 0xF3, 0xC0,
  0x0B, 0xB8, 0x00, 0xBB, 0x80,
  0x07, 0xF4, 0x00, 0x7F, 0x40,
  0x03, 0xF0, 0x00, 0x3F, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0058[ 56] = { /* code 0058, LATIN CAPITAL LETTER X */
  0x2F, 0x00, 0x3E, 0x00,
  0x0F, 0x80, 0xBC, 0x00,
  0x03, 0xD1, 0xF0, 0x00,
  0x02, 0xF3, 0xE0, 0x00,
  0x00, 0xFB, 0xC0, 0x00,
  0x00, 0x3F, 0x00, 0x00,
  0x00, 0x2E, 0x00, 0x00,
  0x00, 0x7F, 0x40, 0x00,
  0x00, 0xF3, 0xC0, 0x00,
  0x03, 0xE2, 0xF0, 0x00,
  0x0B, 0xC0, 0xF8, 0x00,
  0x0F, 0x40, 0x7C, 0x00,
  0x3E, 0x00, 0x2F, 0x00,
  0xBC, 0x00, 0x0F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0059[ 42] = { /* code 0059, LATIN CAPITAL LETTER Y */
  0xB8, 0x00, 0x2E,
  0x3D, 0x00, 0x7C,
  0x1F, 0x00, 0xF4,
  0x0F, 0x82, 0xF0,
  0x03, 0xC3, 0xC0,
  0x02, 0xE7, 0x80,
  0x00, 0xFF, 0x00,
  0x00, 0x7D, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0x3C, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_005A[ 42] = { /* code 005A, LATIN CAPITAL LETTER Z */
  0x3F, 0xFF, 0xFC,
  0x3F, 0xFF, 0xF8,
  0x00, 0x00, 0xF0,
  0x00, 0x03, 0xC0,
  0x00, 0x0B, 0x40,
  0x00, 0x1E, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0xF0, 0x00,
  0x02, 0xD0, 0x00,
  0x07, 0x80, 0x00,
  0x1F, 0x00, 0x00,
  0x3C, 0x00, 0x00,
  0xBF, 0xFF, 0xFC,
  0xFF, 0xFF, 0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial22_0077[ 40] = { /* code 0077, LATIN SMALL LETTER W */
  0x7C, 0x07, 0x40, 0xF4,
  0x3C, 0x0B, 0x80, 0xF0,
  0x3D, 0x0F, 0xC1, 0xE0,
  0x1E, 0x1E, 0xD2, 0xD0,
  0x0F, 0x2C, 0xE2, 0xC0,
  0x0F, 0x38, 0xB3, 0xC0,
  0x07, 0xB4, 0x7B, 0x40,
  0x03, 0xF0, 0x3F, 0x00,
  0x03, 0xF0, 0x3F, 0x00,
  0x01, 0xE0, 0x2D, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontArial22_CharInfo[41] = {
   {   1,   1,   0,  18,   5, acGUI_FontArial22_0020 } /* code 0020, SPACE */
  ,{  12,  14,   1,   4,  13, acGUI_FontArial22_0026 } /* code 0026, AMPERSAND */
  ,{   2,   2,   2,  16,   5, acGUI_FontArial22_002E } /* code 002E, FULL STOP */
  ,{   9,  14,   1,   4,  11, acGUI_FontArial22_0030 } /* code 0030, DIGIT ZERO */
  ,{   5,  14,   2,   4,  11, acGUI_FontArial22_0031 } /* code 0031, DIGIT ONE */
  ,{   9,  14,   1,   4,  11, acGUI_FontArial22_0032 } /* code 0032, DIGIT TWO */
  ,{   9,  14,   1,   4,  11, acGUI_FontArial22_0033 } /* code 0033, DIGIT THREE */
  ,{  10,  14,   0,   4,  11, acGUI_FontArial22_0034 } /* code 0034, DIGIT FOUR */
  ,{   9,  14,   1,   4,  11, acGUI_FontArial22_0035 } /* code 0035, DIGIT FIVE */
  ,{   9,  14,   1,   4,  11, acGUI_FontArial22_0036 } /* code 0036, DIGIT SIX */
  ,{   9,  14,   1,   4,  11, acGUI_FontArial22_0037 } /* code 0037, DIGIT SEVEN */
  ,{   9,  14,   1,   4,  11, acGUI_FontArial22_0038 } /* code 0038, DIGIT EIGHT */
  ,{   9,  14,   1,   4,  11, acGUI_FontArial22_0039 } /* code 0039, DIGIT NINE */
  ,{   2,  10,   2,   8,   5, acGUI_FontArial22_003A } /* code 003A, COLON */
  ,{  15,  14,  -1,   4,  13, acGUI_FontArial22_0041 } /* code 0041, LATIN CAPITAL LETTER A */
  ,{  10,  14,   2,   4,  13, acGUI_FontArial22_0042 } /* code 0042, LATIN CAPITAL LETTER B */
  ,{  13,  14,   1,   4,  14, acGUI_FontArial22_0043 } /* code 0043, LATIN CAPITAL LETTER C */
  ,{  11,  14,   2,   4,  14, acGUI_FontArial22_0044 } /* code 0044, LATIN CAPITAL LETTER D */
  ,{  10,  14,   2,   4,  13, acGUI_FontArial22_0045 } /* code 0045, LATIN CAPITAL LETTER E */
  ,{   9,  14,   2,   4,  12, acGUI_FontArial22_0046 } /* code 0046, LATIN CAPITAL LETTER F */
  ,{  13,  14,   1,   4,  15, acGUI_FontArial22_0047 } /* code 0047, LATIN CAPITAL LETTER G */
  ,{  11,  14,   1,   4,  13, acGUI_FontArial22_0048 } /* code 0048, LATIN CAPITAL LETTER H */
  ,{   2,  14,   2,   4,   6, acGUI_FontArial22_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{   7,  14,   1,   4,  10, acGUI_FontArial22_004A } /* code 004A, LATIN CAPITAL LETTER J */
  ,{  11,  14,   2,   4,  13, acGUI_FontArial22_004B } /* code 004B, LATIN CAPITAL LETTER K */
  ,{   8,  14,   2,   4,  11, acGUI_FontArial22_004C } /* code 004C, LATIN CAPITAL LETTER L */
  ,{  13,  14,   1,   4,  15, acGUI_FontArial22_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  11,  14,   1,   4,  13, acGUI_FontArial22_004E } /* code 004E, LATIN CAPITAL LETTER N */
  ,{  13,  14,   1,   4,  15, acGUI_FontArial22_004F } /* code 004F, LATIN CAPITAL LETTER O */
  ,{  10,  14,   2,   4,  13, acGUI_FontArial22_0050 } /* code 0050, LATIN CAPITAL LETTER P */
  ,{  13,  15,   1,   4,  15, acGUI_FontArial22_0051 } /* code 0051, LATIN CAPITAL LETTER Q */
  ,{  11,  14,   2,   4,  14, acGUI_FontArial22_0052 } /* code 0052, LATIN CAPITAL LETTER R */
  ,{  11,  14,   1,   4,  13, acGUI_FontArial22_0053 } /* code 0053, LATIN CAPITAL LETTER S */
  ,{  10,  14,   1,   4,  12, acGUI_FontArial22_0054 } /* code 0054, LATIN CAPITAL LETTER T */
  ,{  11,  14,   1,   4,  13, acGUI_FontArial22_0055 } /* code 0055, LATIN CAPITAL LETTER U */
  ,{  15,  14,  -1,   4,  13, acGUI_FontArial22_0056 } /* code 0056, LATIN CAPITAL LETTER V */
  ,{  19,  14,   0,   4,  19, acGUI_FontArial22_0057 } /* code 0057, LATIN CAPITAL LETTER W */
  ,{  13,  14,   0,   4,  13, acGUI_FontArial22_0058 } /* code 0058, LATIN CAPITAL LETTER X */
  ,{  12,  14,   0,   4,  12, acGUI_FontArial22_0059 } /* code 0059, LATIN CAPITAL LETTER Y */
  ,{  11,  14,   0,   4,  12, acGUI_FontArial22_005A } /* code 005A, LATIN CAPITAL LETTER Z */
  ,{  15,  10,  -1,   8,  13, acGUI_FontArial22_0077 } /* code 0077, LATIN SMALL LETTER W */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial22_Prop6 = {
   0x0077 /* first character */
  ,0x0077 /* last character  */
  ,&GUI_FontArial22_CharInfo[ 40] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial22_Prop5 = {
   0x0041 /* first character */
  ,0x005A /* last character  */
  ,&GUI_FontArial22_CharInfo[ 14] /* address of first character */
  ,&GUI_FontArial22_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial22_Prop4 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontArial22_CharInfo[  3] /* address of first character */
  ,&GUI_FontArial22_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial22_Prop3 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontArial22_CharInfo[  2] /* address of first character */
  ,&GUI_FontArial22_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial22_Prop2 = {
   0x0026 /* first character */
  ,0x0026 /* last character  */
  ,&GUI_FontArial22_CharInfo[  1] /* address of first character */
  ,&GUI_FontArial22_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial22_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontArial22_CharInfo[  0] /* address of first character */
  ,&GUI_FontArial22_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontArial22 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontArial22_Prop1}
  ,18 /* Baseline */
  ,10 /* Height of lowercase characters */
  ,14 /* Height of capital characters */
};

