/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial17.c                                             *
* Font:        Arial                                                 *
* Height:      17                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  17                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character disabled:  0x39 (57)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x2E (46)                                     *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Move/Left        at character 0x2E (46)                       *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial17;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_002E[  1] = { /* code 002E, FULL STOP */
  0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0030[ 22] = { /* code 0030, DIGIT ZERO */
  0x2F, 0x80,
  0x50, 0xB0,
  0x80, 0x30,
  0xC0, 0x30,
  0xC0, 0x30,
  0xC0, 0x30,
  0xC0, 0x30,
  0xC0, 0x30,
  0x80, 0x30,
  0x50, 0x70,
  0x2F, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0031[ 11] = { /* code 0031, DIGIT ONE */
  0x0C,
  0x2C,
  0x9C,
  0x4C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C,
  0x0C
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0032[ 22] = { /* code 0032, DIGIT TWO */
  0x2F, 0x80,
  0x90, 0x60,
  0xC0, 0x30,
  0x00, 0x30,
  0x00, 0x20,
  0x00, 0x80,
  0x01, 0x40,
  0x02, 0x00,
  0x08, 0x00,
  0x70, 0x00,
  0xFF, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0033[ 22] = { /* code 0033, DIGIT THREE */
  0x2F, 0x80,
  0x60, 0x60,
  0xC0, 0x30,
  0x00, 0x30,
  0x00, 0x50,
  0x0B, 0xC0,
  0x00, 0xB0,
  0x00, 0x30,
  0xC0, 0x30,
  0xA0, 0xA0,
  0x2F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0034[ 22] = { /* code 0034, DIGIT FOUR */
  0x00, 0x70,
  0x00, 0xF0,
  0x02, 0x30,
  0x09, 0x30,
  0x08, 0x30,
  0x30, 0x30,
  0x90, 0x30,
  0xFF, 0xFC,
  0x00, 0x30,
  0x00, 0x30,
  0x00, 0x30
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0035[ 22] = { /* code 0035, DIGIT FIVE */
  0x3F, 0xF0,
  0x20, 0x00,
  0x60, 0x00,
  0x90, 0x00,
  0xAF, 0x80,
  0xD0, 0x60,
  0x00, 0x30,
  0x00, 0x30,
  0xC0, 0x30,
  0x90, 0x50,
  0x2F, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0036[ 22] = { /* code 0036, DIGIT SIX */
  0x2F, 0x80,
  0x50, 0x60,
  0x80, 0x30,
  0xC0, 0x00,
  0xCF, 0x80,
  0xE0, 0xA0,
  0xC0, 0x30,
  0xC0, 0x30,
  0x80, 0x30,
  0x50, 0xA0,
  0x1F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0037[ 22] = { /* code 0037, DIGIT SEVEN */
  0xFF, 0xF0,
  0x00, 0x60,
  0x00, 0xC0,
  0x01, 0x80,
  0x02, 0x40,
  0x03, 0x00,
  0x06, 0x00,
  0x09, 0x00,
  0x08, 0x00,
  0x0C, 0x00,
  0x0C, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0038[ 22] = { /* code 0038, DIGIT EIGHT */
  0x2F, 0x80,
  0x90, 0x60,
  0xC0, 0x30,
  0xC0, 0x30,
  0x90, 0x60,
  0x3F, 0xC0,
  0x90, 0x60,
  0xC0, 0x30,
  0xC0, 0x30,
  0x90, 0x60,
  0x2F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial17_0039[ 22] = { /* code 0039, DIGIT NINE */
  0x2F, 0x80,
  0xA0, 0xA0,
  0xC0, 0x30,
  0xC0, 0x30,
  0xC0, 0x30,
  0xA0, 0xB0,
  0x2F, 0x70,
  0x00, 0x30,
  0xC0, 0x70,
  0xA0, 0xA0,
  0x2F, 0x40
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontArial17_CharInfo[12] = {
   {   1,   1,   0,  14,   4, acGUI_FontArial17_0020 } /* code 0020, SPACE */
  ,{   1,   1,   1,  13,   3, acGUI_FontArial17_002E } /* code 002E, FULL STOP */
  ,{   7,  11,   1,   3,   8, acGUI_FontArial17_0030 } /* code 0030, DIGIT ZERO */
  ,{   3,  11,   2,   3,   8, acGUI_FontArial17_0031 } /* code 0031, DIGIT ONE */
  ,{   6,  11,   1,   3,   8, acGUI_FontArial17_0032 } /* code 0032, DIGIT TWO */
  ,{   6,  11,   1,   3,   8, acGUI_FontArial17_0033 } /* code 0033, DIGIT THREE */
  ,{   7,  11,   0,   3,   8, acGUI_FontArial17_0034 } /* code 0034, DIGIT FOUR */
  ,{   6,  11,   1,   3,   8, acGUI_FontArial17_0035 } /* code 0035, DIGIT FIVE */
  ,{   6,  11,   1,   3,   8, acGUI_FontArial17_0036 } /* code 0036, DIGIT SIX */
  ,{   6,  11,   1,   3,   8, acGUI_FontArial17_0037 } /* code 0037, DIGIT SEVEN */
  ,{   6,  11,   1,   3,   8, acGUI_FontArial17_0038 } /* code 0038, DIGIT EIGHT */
  ,{   6,  11,   1,   3,   8, acGUI_FontArial17_0039 } /* code 0039, DIGIT NINE */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial17_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontArial17_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial17_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontArial17_CharInfo[  1] /* address of first character */
  ,&GUI_FontArial17_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial17_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontArial17_CharInfo[  0] /* address of first character */
  ,&GUI_FontArial17_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontArial17 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,17 /* height of font  */
  ,17 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontArial17_Prop1}
  ,14 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

