/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Arial27.c                                             *
* Font:        Arial                                                 *
* Height:      27                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  27                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x20 (32)                                     *
* Character enabled:   0x2E (46)                                     *
* Character enabled:   0x30 (48)                                     *
* Character enabled:   0x31 (49)                                     *
* Character enabled:   0x32 (50)                                     *
* Character enabled:   0x33 (51)                                     *
* Character enabled:   0x34 (52)                                     *
* Character enabled:   0x35 (53)                                     *
* Character enabled:   0x36 (54)                                     *
* Character enabled:   0x37 (55)                                     *
* Character enabled:   0x38 (56)                                     *
* Character enabled:   0x39 (57)                                     *
* Character enabled:   0x25 (37)                                     *
* Character enabled:   0x26 (38)                                     *
* Character enabled:   0x4D (77)                                     *
* Character enabled:   0x49 (73)                                     *
* Character enabled:   0x4E (78)                                     *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Cursor Distance/Decrease at character 0x2E (46)               *
* Edit/Move/Left        at character 0x2E (46)                       *
* Pixel index of character 0x26 (38) at 0/10 set to 0                *
* Pixel index of character 0x26 (38) at 0/11 set to 0                *
* Pixel index of character 0x26 (38) at 0/12 set to 0                *
* Pixel index of character 0x26 (38) at 0/13 set to 0                *
* Pixel index of character 0x26 (38) at 0/14 set to 0                *
* Pixel index of character 0x26 (38) at 1/13 set to 0                *
* Pixel index of character 0x26 (38) at 1/13 set to 0                *
* Pixel index of character 0x26 (38) at 1/11 set to 0                *
* Pixel index of character 0x26 (38) at 1/10 set to 0                *
* Pixel index of character 0x26 (38) at 1/9 set to 0                 *
* Pixel index of character 0x26 (38) at 1/8 set to 0                 *
* Pixel index of character 0x26 (38) at 1/7 set to 0                 *
* Pixel index of character 0x26 (38) at 1/6 set to 0                 *
* Pixel index of character 0x26 (38) at 1/5 set to 0                 *
* Pixel index of character 0x26 (38) at 1/4 set to 0                 *
* Pixel index of character 0x26 (38) at 1/3 set to 0                 *
* Pixel index of character 0x26 (38) at 1/2 set to 0                 *
* Pixel index of character 0x26 (38) at 2/2 set to 0                 *
* Pixel index of character 0x26 (38) at 2/3 set to 0                 *
* Pixel index of character 0x26 (38) at 2/4 set to 0                 *
* Pixel index of character 0x26 (38) at 2/5 set to 0                 *
* Pixel index of character 0x26 (38) at 2/6 set to 0                 *
* Pixel index of character 0x26 (38) at 2/7 set to 0                 *
* Pixel index of character 0x26 (38) at 2/8 set to 0                 *
* Pixel index of character 0x26 (38) at 2/9 set to 0                 *
* Pixel index of character 0x26 (38) at 2/10 set to 0                *
* Pixel index of character 0x26 (38) at 2/11 set to 0                *
* Pixel index of character 0x26 (38) at 2/12 set to 0                *
* Pixel index of character 0x26 (38) at 2/13 set to 0                *
* Pixel index of character 0x26 (38) at 2/14 set to 0                *
* Pixel index of character 0x26 (38) at 2/15 set to 0                *
* Pixel index of character 0x26 (38) at 2/16 set to 0                *
* Pixel index of character 0x26 (38) at 1/15 set to 0                *
* Pixel index of character 0x26 (38) at 1/14 set to 0                *
* Pixel index of character 0x26 (38) at 1/13 set to 0                *
* Pixel index of character 0x26 (38) at 1/12 set to 0                *
* Pixel index of character 0x26 (38) at 5/16 set to 0                *
* Pixel index of character 0x26 (38) at 4/16 set to 0                *
* Pixel index of character 0x26 (38) at 3/16 set to 0                *
* Pixel index of character 0x26 (38) at 2/16 set to 0                *
* Pixel index of character 0x26 (38) at 3/15 set to 0                *
* Pixel index of character 0x26 (38) at 4/15 set to 0                *
* Pixel index of character 0x26 (38) at 5/15 set to 0                *
* Pixel index of character 0x26 (38) at 6/15 set to 0                *
* Pixel index of character 0x26 (38) at 7/15 set to 0                *
* Pixel index of character 0x26 (38) at 7/16 set to 0                *
* Pixel index of character 0x26 (38) at 6/16 set to 0                *
* Pixel index of character 0x26 (38) at 5/16 set to 0                *
* Pixel index of character 0x26 (38) at 5/15 set to 0                *
* Pixel index of character 0x26 (38) at 5/14 set to 0                *
* Pixel index of character 0x26 (38) at 4/14 set to 0                *
* Pixel index of character 0x26 (38) at 3/14 set to 0                *
* Pixel index of character 0x26 (38) at 3/14 set to 0                *
* Pixel index of character 0x26 (38) at 4/14 set to 0                *
* Pixel index of character 0x26 (38) at 5/14 set to 0                *
* Pixel index of character 0x26 (38) at 6/14 set to 0                *
* Pixel index of character 0x26 (38) at 7/14 set to 0                *
* Pixel index of character 0x26 (38) at 8/14 set to 0                *
* Pixel index of character 0x26 (38) at 9/14 set to 0                *
* Pixel index of character 0x26 (38) at 10/14 set to 0               *
* Pixel index of character 0x26 (38) at 11/14 set to 0               *
* Pixel index of character 0x26 (38) at 12/14 set to 0               *
* Pixel index of character 0x26 (38) at 13/14 set to 0               *
* Pixel index of character 0x26 (38) at 0/14 set to 0                *
* Pixel index of character 0x26 (38) at 0/15 set to 0                *
* Pixel index of character 0x26 (38) at 1/15 set to 0                *
* Pixel index of character 0x26 (38) at 1/15 set to 0                *
* Pixel index of character 0x26 (38) at 2/15 set to 0                *
* Pixel index of character 0x26 (38) at 3/15 set to 0                *
* Pixel index of character 0x26 (38) at 4/15 set to 0                *
* Pixel index of character 0x26 (38) at 5/15 set to 0                *
* Pixel index of character 0x26 (38) at 6/15 set to 0                *
* Pixel index of character 0x26 (38) at 7/15 set to 0                *
* Pixel index of character 0x26 (38) at 8/15 set to 0                *
* Pixel index of character 0x26 (38) at 9/15 set to 0                *
* Pixel index of character 0x26 (38) at 10/15 set to 0               *
* Pixel index of character 0x26 (38) at 11/15 set to 0               *
* Pixel index of character 0x26 (38) at 12/15 set to 0               *
* Pixel index of character 0x26 (38) at 13/15 set to 0               *
* Pixel index of character 0x26 (38) at 0/15 set to 0                *
* Pixel index of character 0x26 (38) at 1/15 set to 0                *
* Pixel index of character 0x26 (38) at 2/15 set to 0                *
* Pixel index of character 0x26 (38) at 3/16 set to 0                *
* Pixel index of character 0x26 (38) at 4/16 set to 0                *
* Pixel index of character 0x26 (38) at 5/16 set to 0                *
* Pixel index of character 0x26 (38) at 6/16 set to 0                *
* Pixel index of character 0x26 (38) at 7/16 set to 0                *
* Pixel index of character 0x26 (38) at 8/16 set to 0                *
* Pixel index of character 0x26 (38) at 9/16 set to 0                *
* Pixel index of character 0x26 (38) at 10/16 set to 0               *
* Pixel index of character 0x26 (38) at 12/16 set to 0               *
* Pixel index of character 0x26 (38) at 13/16 set to 0               *
* Pixel index of character 0x26 (38) at 12/16 set to 0               *
* Pixel index of character 0x26 (38) at 11/16 set to 0               *
* Pixel index of character 0x26 (38) at 10/16 set to 0               *
* Pixel index of character 0x26 (38) at 10/15 set to 0               *
* Pixel index of character 0x26 (38) at 10/14 set to 0               *
* Pixel index of character 0x26 (38) at 10/13 set to 0               *
* Pixel index of character 0x26 (38) at 10/12 set to 0               *
* Pixel index of character 0x26 (38) at 10/11 set to 0               *
* Pixel index of character 0x26 (38) at 10/10 set to 0               *
* Pixel index of character 0x26 (38) at 10/9 set to 0                *
* Pixel index of character 0x26 (38) at 11/9 set to 0                *
* Pixel index of character 0x26 (38) at 12/9 set to 0                *
* Pixel index of character 0x26 (38) at 13/9 set to 0                *
* Pixel index of character 0x26 (38) at 13/10 set to 0               *
* Pixel index of character 0x26 (38) at 12/10 set to 0               *
* Pixel index of character 0x26 (38) at 11/10 set to 0               *
* Pixel index of character 0x26 (38) at 10/10 set to 0               *
* Pixel index of character 0x26 (38) at 10/11 set to 0               *
* Pixel index of character 0x26 (38) at 11/11 set to 0               *
* Pixel index of character 0x26 (38) at 12/11 set to 0               *
* Pixel index of character 0x26 (38) at 12/12 set to 0               *
* Pixel index of character 0x26 (38) at 11/13 set to 0               *
* Pixel index of character 0x26 (38) at 11/12 set to 0               *
* Pixel index of character 0x26 (38) at 11/11 set to 0               *
* Pixel index of character 0x26 (38) at 10/11 set to 0               *
* Pixel index of character 0x26 (38) at 9/12 set to 0                *
* Pixel index of character 0x26 (38) at 9/13 set to 0                *
* Pixel index of character 0x26 (38) at 9/13 set to 0                *
* Pixel index of character 0x26 (38) at 9/12 set to 0                *
* Pixel index of character 0x26 (38) at 9/11 set to 0                *
* Pixel index of character 0x26 (38) at 9/10 set to 0                *
* Pixel index of character 0x26 (38) at 9/9 set to 0                 *
* Pixel index of character 0x26 (38) at 9/8 set to 0                 *
* Pixel index of character 0x26 (38) at 9/7 set to 0                 *
* Pixel index of character 0x26 (38) at 9/6 set to 0                 *
* Pixel index of character 0x26 (38) at 9/5 set to 0                 *
* Pixel index of character 0x26 (38) at 9/4 set to 0                 *
* Pixel index of character 0x26 (38) at 9/3 set to 0                 *
* Pixel index of character 0x26 (38) at 9/2 set to 0                 *
* Pixel index of character 0x26 (38) at 9/1 set to 0                 *
* Pixel index of character 0x26 (38) at 8/0 set to 0                 *
* Pixel index of character 0x26 (38) at 8/1 set to 0                 *
* Pixel index of character 0x26 (38) at 8/2 set to 0                 *
* Pixel index of character 0x26 (38) at 8/3 set to 0                 *
* Pixel index of character 0x26 (38) at 8/4 set to 0                 *
* Pixel index of character 0x26 (38) at 8/5 set to 0                 *
* Pixel index of character 0x26 (38) at 8/6 set to 0                 *
* Pixel index of character 0x26 (38) at 8/7 set to 0                 *
* Pixel index of character 0x26 (38) at 8/8 set to 0                 *
* Pixel index of character 0x26 (38) at 8/9 set to 0                 *
* Pixel index of character 0x26 (38) at 8/10 set to 0                *
* Pixel index of character 0x26 (38) at 8/11 set to 0                *
* Pixel index of character 0x26 (38) at 8/12 set to 0                *
* Pixel index of character 0x26 (38) at 7/12 set to 0                *
* Pixel index of character 0x26 (38) at 7/11 set to 0                *
* Pixel index of character 0x26 (38) at 7/10 set to 0                *
* Pixel index of character 0x26 (38) at 7/9 set to 0                 *
* Pixel index of character 0x26 (38) at 7/8 set to 0                 *
* Pixel index of character 0x26 (38) at 7/7 set to 0                 *
* Pixel index of character 0x26 (38) at 7/6 set to 0                 *
* Pixel index of character 0x26 (38) at 7/5 set to 0                 *
* Pixel index of character 0x26 (38) at 7/4 set to 0                 *
* Pixel index of character 0x26 (38) at 7/3 set to 0                 *
* Pixel index of character 0x26 (38) at 7/2 set to 0                 *
* Pixel index of character 0x26 (38) at 7/1 set to 0                 *
* Pixel index of character 0x26 (38) at 7/0 set to 0                 *
* Pixel index of character 0x26 (38) at 6/0 set to 0                 *
* Pixel index of character 0x26 (38) at 6/1 set to 0                 *
* Pixel index of character 0x26 (38) at 5/1 set to 0                 *
* Pixel index of character 0x26 (38) at 5/0 set to 0                 *
* Pixel index of character 0x26 (38) at 4/0 set to 0                 *
* Pixel index of character 0x26 (38) at 4/1 set to 0                 *
* Pixel index of character 0x26 (38) at 4/2 set to 0                 *
* Pixel index of character 0x26 (38) at 3/1 set to 0                 *
* Pixel index of character 0x26 (38) at 3/2 set to 0                 *
* Pixel index of character 0x26 (38) at 3/3 set to 0                 *
* Pixel index of character 0x26 (38) at 3/4 set to 0                 *
* Pixel index of character 0x26 (38) at 3/5 set to 0                 *
* Pixel index of character 0x26 (38) at 3/6 set to 0                 *
* Pixel index of character 0x26 (38) at 3/7 set to 0                 *
* Pixel index of character 0x26 (38) at 3/8 set to 0                 *
* Pixel index of character 0x26 (38) at 4/8 set to 0                 *
* Pixel index of character 0x26 (38) at 5/8 set to 0                 *
* Pixel index of character 0x26 (38) at 6/8 set to 0                 *
* Pixel index of character 0x26 (38) at 6/9 set to 0                 *
* Pixel index of character 0x26 (38) at 6/10 set to 0                *
* Pixel index of character 0x26 (38) at 3/9 set to 0                 *
* Pixel index of character 0x26 (38) at 3/8 set to 0                 *
* Pixel index of character 0x26 (38) at 3/7 set to 0                 *
* Pixel index of character 0x26 (38) at 4/7 set to 0                 *
* Pixel index of character 0x26 (38) at 5/7 set to 0                 *
* Pixel index of character 0x26 (38) at 6/7 set to 0                 *
* Pixel index of character 0x26 (38) at 6/6 set to 0                 *
* Pixel index of character 0x26 (38) at 6/6 set to 0                 *
* Pixel index of character 0x26 (38) at 5/6 set to 0                 *
* Pixel index of character 0x26 (38) at 4/6 set to 0                 *
* Pixel index of character 0x26 (38) at 3/6 set to 0                 *
* Pixel index of character 0x26 (38) at 3/5 set to 0                 *
* Pixel index of character 0x26 (38) at 4/5 set to 0                 *
* Pixel index of character 0x26 (38) at 5/5 set to 0                 *
* Pixel index of character 0x26 (38) at 0/16 set to 3                *
* Pixel index of character 0x26 (38) at 1/16 set to 3                *
* Pixel index of character 0x26 (38) at 2/16 set to 3                *
* Pixel index of character 0x26 (38) at 0/15 set to 3                *
* Pixel index of character 0x26 (38) at 1/15 set to 3                *
* Pixel index of character 0x26 (38) at 2/15 set to 3                *
* Pixel index of character 0x26 (38) at 13/16 set to 3               *
* Pixel index of character 0x26 (38) at 12/16 set to 3               *
* Pixel index of character 0x26 (38) at 12/15 set to 3               *
* Pixel index of character 0x26 (38) at 13/15 set to 3               *
* Pixel index of character 0x26 (38) at 11/15 set to 3               *
* Pixel index of character 0x26 (38) at 11/16 set to 3               *
* Pixel index of character 0x26 (38) at 3/15 set to 3                *
* Pixel index of character 0x26 (38) at 3/16 set to 3                *
* Pixel index of character 0x26 (38) at 10/15 set to 3               *
* Pixel index of character 0x26 (38) at 10/16 set to 3               *
* Pixel index of character 0x26 (38) at 9/15 set to 3                *
* Pixel index of character 0x26 (38) at 9/16 set to 3                *
* Pixel index of character 0x26 (38) at 4/15 set to 3                *
* Pixel index of character 0x26 (38) at 4/16 set to 3                *
* Pixel index of character 0x26 (38) at 4/14 set to 3                *
* Pixel index of character 0x26 (38) at 3/13 set to 3                *
* Pixel index of character 0x26 (38) at 2/12 set to 3                *
* Pixel index of character 0x26 (38) at 1/11 set to 3                *
* Pixel index of character 0x26 (38) at 0/10 set to 3                *
* Pixel index of character 0x26 (38) at 0/8 set to 3                 *
* Pixel index of character 0x26 (38) at 0/9 set to 3                 *
* Pixel index of character 0x26 (38) at 0/7 set to 3                 *
* Pixel index of character 0x26 (38) at 0/6 set to 3                 *
* Pixel index of character 0x26 (38) at 0/5 set to 3                 *
* Pixel index of character 0x26 (38) at 0/4 set to 3                 *
* Pixel index of character 0x26 (38) at 1/3 set to 3                 *
* Pixel index of character 0x26 (38) at 2/2 set to 3                 *
* Pixel index of character 0x26 (38) at 3/1 set to 3                 *
* Pixel index of character 0x26 (38) at 4/0 set to 3                 *
* Pixel index of character 0x26 (38) at 5/0 set to 3                 *
* Pixel index of character 0x26 (38) at 6/0 set to 3                 *
* Pixel index of character 0x26 (38) at 7/0 set to 3                 *
* Pixel index of character 0x26 (38) at 8/0 set to 3                 *
* Pixel index of character 0x26 (38) at 9/0 set to 3                 *
* Pixel index of character 0x26 (38) at 10/1 set to 3                *
* Pixel index of character 0x26 (38) at 11/2 set to 3                *
* Pixel index of character 0x26 (38) at 12/3 set to 3                *
* Pixel index of character 0x26 (38) at 13/4 set to 3                *
* Pixel index of character 0x26 (38) at 13/5 set to 3                *
* Pixel index of character 0x26 (38) at 13/6 set to 3                *
* Pixel index of character 0x26 (38) at 13/7 set to 3                *
* Pixel index of character 0x26 (38) at 13/8 set to 3                *
* Pixel index of character 0x26 (38) at 13/9 set to 3                *
* Pixel index of character 0x26 (38) at 13/10 set to 3               *
* Pixel index of character 0x26 (38) at 12/11 set to 3               *
* Pixel index of character 0x26 (38) at 11/12 set to 3               *
* Pixel index of character 0x26 (38) at 10/13 set to 3               *
* Pixel index of character 0x26 (38) at 9/14 set to 3                *
* Pixel index of character 0x26 (38) at 5/1 set to 3                 *
* Pixel index of character 0x26 (38) at 6/1 set to 3                 *
* Pixel index of character 0x26 (38) at 8/1 set to 3                 *
* Pixel index of character 0x26 (38) at 7/1 set to 3                 *
* Pixel index of character 0x26 (38) at 9/1 set to 3                 *
* Pixel index of character 0x26 (38) at 4/1 set to 3                 *
* Pixel index of character 0x26 (38) at 3/2 set to 3                 *
* Pixel index of character 0x26 (38) at 2/3 set to 3                 *
* Pixel index of character 0x26 (38) at 1/4 set to 3                 *
* Pixel index of character 0x26 (38) at 1/5 set to 3                 *
* Pixel index of character 0x26 (38) at 1/6 set to 3                 *
* Pixel index of character 0x26 (38) at 1/7 set to 3                 *
* Pixel index of character 0x26 (38) at 1/8 set to 3                 *
* Pixel index of character 0x26 (38) at 1/9 set to 3                 *
* Pixel index of character 0x26 (38) at 1/10 set to 3                *
* Pixel index of character 0x26 (38) at 2/11 set to 3                *
* Pixel index of character 0x26 (38) at 2/12 set to 3                *
* Pixel index of character 0x26 (38) at 3/12 set to 3                *
* Pixel index of character 0x26 (38) at 4/13 set to 3                *
* Pixel index of character 0x26 (38) at 9/13 set to 3                *
* Pixel index of character 0x26 (38) at 10/12 set to 3               *
* Pixel index of character 0x26 (38) at 11/11 set to 3               *
* Pixel index of character 0x26 (38) at 12/10 set to 3               *
* Pixel index of character 0x26 (38) at 12/9 set to 3                *
* Pixel index of character 0x26 (38) at 12/8 set to 3                *
* Pixel index of character 0x26 (38) at 12/7 set to 3                *
* Pixel index of character 0x26 (38) at 12/6 set to 3                *
* Pixel index of character 0x26 (38) at 12/5 set to 3                *
* Pixel index of character 0x26 (38) at 12/4 set to 3                *
* Pixel index of character 0x26 (38) at 11/3 set to 3                *
* Pixel index of character 0x26 (38) at 10/2 set to 3                *
* Pixel index of character 0x26 (38) at 3/0 set to 1                 *
* Pixel index of character 0x26 (38) at 2/1 set to 2                 *
* Pixel index of character 0x26 (38) at 1/2 set to 2                 *
* Pixel index of character 0x26 (38) at 0/3 set to 1                 *
* Pixel index of character 0x26 (38) at 2/4 set to 1                 *
* Pixel index of character 0x26 (38) at 3/3 set to 1                 *
* Pixel index of character 0x26 (38) at 4/2 set to 1                 *
* Pixel index of character 0x26 (38) at 0/11 set to 1                *
* Pixel index of character 0x26 (38) at 1/12 set to 2                *
* Pixel index of character 0x26 (38) at 2/13 set to 2                *
* Pixel index of character 0x26 (38) at 3/14 set to 1                *
* Pixel index of character 0x26 (38) at 2/10 set to 1                *
* Pixel index of character 0x26 (38) at 3/11 set to 1                *
* Pixel index of character 0x26 (38) at 4/12 set to 1                *
* Pixel index of character 0x26 (38) at 10/14 set to 2               *
* Pixel index of character 0x26 (38) at 3/14 set to 2                *
* Pixel index of character 0x26 (38) at 9/12 set to 1                *
* Pixel index of character 0x26 (38) at 10/11 set to 1               *
* Pixel index of character 0x26 (38) at 11/10 set to 1               *
* Pixel index of character 0x26 (38) at 11/13 set to 2               *
* Pixel index of character 0x26 (38) at 12/12 set to 2               *
* Pixel index of character 0x26 (38) at 13/11 set to 1               *
* Pixel index of character 0x26 (38) at 13/3 set to 1                *
* Pixel index of character 0x26 (38) at 12/2 set to 1                *
* Pixel index of character 0x26 (38) at 12/2 set to 2                *
* Pixel index of character 0x26 (38) at 11/1 set to 2                *
* Pixel index of character 0x26 (38) at 10/0 set to 1                *
* Pixel index of character 0x26 (38) at 9/2 set to 1                 *
* Pixel index of character 0x26 (38) at 10/3 set to 1                *
* Pixel index of character 0x26 (38) at 11/4 set to 1                *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontArial27;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0020[  1] = { /* code 0020, SPACE */
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0025[ 85] = { /* code 0025, PERCENT SIGN */
  0x0F, 0xE0, 0x00, 0x3C, 0x00,
  0x3C, 0x3C, 0x00, 0xB4, 0x00,
  0xB0, 0x0E, 0x00, 0xF0, 0x00,
  0xF0, 0x0F, 0x02, 0xD0, 0x00,
  0xF0, 0x0F, 0x07, 0xC0, 0x00,
  0xF0, 0x0F, 0x0F, 0x40, 0x00,
  0xB0, 0x0E, 0x1F, 0x00, 0x00,
  0x3C, 0x3C, 0x3D, 0x00, 0x00,
  0x0B, 0xE0, 0x78, 0x3F, 0x80,
  0x00, 0x00, 0xF0, 0xF0, 0xF0,
  0x00, 0x01, 0xE2, 0xC0, 0x38,
  0x00, 0x03, 0xC3, 0xC0, 0x3C,
  0x00, 0x0B, 0x83, 0xC0, 0x3C,
  0x00, 0x0F, 0x03, 0xC0, 0x3C,
  0x00, 0x2D, 0x02, 0xC0, 0x38,
  0x00, 0x3C, 0x00, 0xF0, 0xF0,
  0x00, 0xB4, 0x00, 0x2F, 0x80
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0026[ 68] = { /* code 0026, AMPERSAND */
  0x01, 0xFF, 0xF4, 0x00,
  0x0B, 0xFF, 0xFE, 0x00,
  0x2F, 0x40, 0x1F, 0x80,
  0x7D, 0x00, 0x07, 0xD0,
  0xF4, 0x00, 0x01, 0xF0,
  0xF0, 0x00, 0x00, 0xF0,
  0xF0, 0x00, 0x00, 0xF0,
  0xF0, 0x00, 0x00, 0xF0,
  0xF0, 0x00, 0x00, 0xF0,
  0xF0, 0x00, 0x00, 0xF0,
  0xF4, 0x00, 0x01, 0xF0,
  0x7D, 0x00, 0x07, 0xD0,
  0x2F, 0x40, 0x1F, 0x80,
  0x0B, 0xC0, 0x3E, 0x00,
  0x02, 0xC0, 0x38, 0x00,
  0xFF, 0xC0, 0x3F, 0xF0,
  0xFF, 0xC0, 0x3F, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_002E[  2] = { /* code 002E, FULL STOP */
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0030[ 51] = { /* code 0030, DIGIT ZERO */
  0x06, 0xFE, 0x40,
  0x1F, 0xFF, 0xD0,
  0x3E, 0x02, 0xF0,
  0x78, 0x00, 0xF4,
  0xB4, 0x00, 0x78,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xB4, 0x00, 0x78,
  0x78, 0x00, 0xB4,
  0x3E, 0x02, 0xF0,
  0x1F, 0xFF, 0xD0,
  0x06, 0xFE, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0031[ 34] = { /* code 0031, DIGIT ONE */
  0x00, 0xB0,
  0x01, 0xF0,
  0x07, 0xF0,
  0x2F, 0xF0,
  0xFC, 0xF0,
  0xE0, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0,
  0x00, 0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0032[ 51] = { /* code 0032, DIGIT TWO */
  0x06, 0xFE, 0x40,
  0x2F, 0xFF, 0xE0,
  0x7D, 0x01, 0xF4,
  0xB4, 0x00, 0x7C,
  0xF0, 0x00, 0x3C,
  0x00, 0x00, 0x3C,
  0x00, 0x00, 0x78,
  0x00, 0x00, 0xF0,
  0x00, 0x02, 0xC0,
  0x00, 0x0B, 0x00,
  0x00, 0x2C, 0x00,
  0x00, 0xB4, 0x00,
  0x03, 0xD0, 0x00,
  0x1F, 0x40, 0x00,
  0x3C, 0x00, 0x00,
  0xBF, 0xFF, 0xFC,
  0xFF, 0xFF, 0xFC
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0033[ 51] = { /* code 0033, DIGIT THREE */
  0x07, 0xFD, 0x00,
  0x2F, 0xFF, 0xC0,
  0x7D, 0x07, 0xE0,
  0xF0, 0x00, 0xF0,
  0x00, 0x00, 0xF0,
  0x00, 0x01, 0xF0,
  0x00, 0x07, 0xD0,
  0x00, 0xBF, 0x40,
  0x00, 0xEF, 0xD0,
  0x00, 0x01, 0xF4,
  0x00, 0x00, 0x7C,
  0x00, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xB8, 0x00, 0x78,
  0x3D, 0x01, 0xF0,
  0x1F, 0xFF, 0xD0,
  0x02, 0xFE, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0034[ 51] = { /* code 0034, DIGIT FOUR */
  0x00, 0x07, 0xC0,
  0x00, 0x0F, 0xC0,
  0x00, 0x2F, 0xC0,
  0x00, 0x3F, 0xC0,
  0x00, 0xF7, 0xC0,
  0x01, 0xE3, 0xC0,
  0x03, 0xC3, 0xC0,
  0x0F, 0x43, 0xC0,
  0x1F, 0x03, 0xC0,
  0x3C, 0x03, 0xC0,
  0xB8, 0x03, 0xC0,
  0xFF, 0xFF, 0xFC,
  0xFF, 0xFF, 0xFC,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0,
  0x00, 0x03, 0xC0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0035[ 51] = { /* code 0035, DIGIT FIVE */
  0x0F, 0xFF, 0xF0,
  0x1F, 0xFF, 0xF0,
  0x2D, 0x00, 0x00,
  0x3C, 0x00, 0x00,
  0x3C, 0x00, 0x00,
  0x39, 0xFE, 0x00,
  0x7F, 0xFF, 0xD0,
  0xBD, 0x01, 0xF0,
  0xF4, 0x00, 0x78,
  0x00, 0x00, 0x3C,
  0x00, 0x00, 0x3C,
  0x00, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xB4, 0x00, 0xB4,
  0x3D, 0x01, 0xF0,
  0x1F, 0xFF, 0xC0,
  0x06, 0xFE, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0036[ 51] = { /* code 0036, DIGIT SIX */
  0x01, 0xFF, 0x80,
  0x0B, 0xFF, 0xF0,
  0x2E, 0x01, 0xF8,
  0x3C, 0x00, 0x3C,
  0x78, 0x00, 0x00,
  0xB4, 0x00, 0x00,
  0xF0, 0xBF, 0x40,
  0xF7, 0xFF, 0xE0,
  0xFE, 0x01, 0xF4,
  0xF8, 0x00, 0x78,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xB0, 0x00, 0x3C,
  0x78, 0x00, 0x78,
  0x3E, 0x01, 0xF0,
  0x0F, 0xFF, 0xD0,
  0x02, 0xFE, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0037[ 51] = { /* code 0037, DIGIT SEVEN */
  0xFF, 0xFF, 0xFC,
  0xFF, 0xFF, 0xFC,
  0x00, 0x00, 0x74,
  0x00, 0x00, 0xE0,
  0x00, 0x03, 0xC0,
  0x00, 0x07, 0x40,
  0x00, 0x0F, 0x00,
  0x00, 0x1D, 0x00,
  0x00, 0x3C, 0x00,
  0x00, 0x78, 0x00,
  0x00, 0xB4, 0x00,
  0x00, 0xF0, 0x00,
  0x01, 0xE0, 0x00,
  0x02, 0xD0, 0x00,
  0x02, 0xD0, 0x00,
  0x03, 0xC0, 0x00,
  0x03, 0xC0, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0038[ 51] = { /* code 0038, DIGIT EIGHT */
  0x02, 0xFE, 0x00,
  0x0F, 0xFF, 0xC0,
  0x2E, 0x02, 0xE0,
  0x3C, 0x00, 0xF0,
  0x3C, 0x00, 0xF0,
  0x3C, 0x00, 0xF0,
  0x1E, 0x02, 0xD0,
  0x07, 0xFF, 0x40,
  0x0F, 0xFF, 0x80,
  0x3D, 0x01, 0xF0,
  0xB4, 0x00, 0x78,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x7C,
  0x7D, 0x01, 0xF4,
  0x2F, 0xFF, 0xE0,
  0x06, 0xFE, 0x40
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0039[ 51] = { /* code 0039, DIGIT NINE */
  0x02, 0xFE, 0x00,
  0x1F, 0xFF, 0xC0,
  0x3D, 0x01, 0xF0,
  0xB8, 0x00, 0xB4,
  0xF0, 0x00, 0x38,
  0xF0, 0x00, 0x3C,
  0xF0, 0x00, 0x3C,
  0xB4, 0x00, 0xBC,
  0x7D, 0x02, 0xFC,
  0x2F, 0xFF, 0x7C,
  0x07, 0xF8, 0x3C,
  0x00, 0x00, 0x78,
  0x00, 0x00, 0xB4,
  0xF0, 0x00, 0xF0,
  0xBC, 0x06, 0xE0,
  0x3F, 0xFF, 0x80,
  0x0B, 0xFD, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_0049[ 17] = { /* code 0049, LATIN CAPITAL LETTER I */
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0,
  0xF0
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_004D[ 68] = { /* code 004D, LATIN CAPITAL LETTER M */
  0xE8, 0x00, 0x00, 0xAC,
  0xFE, 0x00, 0x02, 0xFC,
  0xFF, 0x00, 0x03, 0xFC,
  0xFB, 0x40, 0x07, 0xBC,
  0xF7, 0x80, 0x0B, 0x7C,
  0xF3, 0xC0, 0x0F, 0x3C,
  0xF2, 0xC0, 0x0E, 0x3C,
  0xF1, 0xD0, 0x1D, 0x3C,
  0xF0, 0xE0, 0x2C, 0x3C,
  0xF0, 0xF0, 0x3C, 0x3C,
  0xF0, 0xB4, 0x78, 0x3C,
  0xF0, 0x38, 0xB4, 0x3C,
  0xF0, 0x3C, 0xF0, 0x3C,
  0xF0, 0x2D, 0xE0, 0x3C,
  0xF0, 0x1F, 0xD0, 0x3C,
  0xF0, 0x0F, 0xC0, 0x3C,
  0xF0, 0x0F, 0xC0, 0x3C
};

GUI_CONST_STORAGE unsigned char acGUI_FontArial27_004E[ 68] = { /* code 004E, LATIN CAPITAL LETTER N */
  0xF4, 0x00, 0x03, 0xC0,
  0xFC, 0x00, 0x03, 0xC0,
  0xFE, 0x00, 0x03, 0xC0,
  0xFF, 0x40, 0x03, 0xC0,
  0xF3, 0xC0, 0x03, 0xC0,
  0xF1, 0xE0, 0x03, 0xC0,
  0xF0, 0xF4, 0x03, 0xC0,
  0xF0, 0x3C, 0x03, 0xC0,
  0xF0, 0x2E, 0x03, 0xC0,
  0xF0, 0x0F, 0x03, 0xC0,
  0xF0, 0x07, 0xC3, 0xC0,
  0xF0, 0x02, 0xD3, 0xC0,
  0xF0, 0x00, 0xF3, 0xC0,
  0xF0, 0x00, 0x7F, 0xC0,
  0xF0, 0x00, 0x2F, 0xC0,
  0xF0, 0x00, 0x0F, 0xC0,
  0xF0, 0x00, 0x07, 0xC0
};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontArial27_CharInfo[17] = {
   {   1,   1,   0,  21,   7, acGUI_FontArial27_0020 } /* code 0020, SPACE */
  ,{  19,  17,   1,   4,  21, acGUI_FontArial27_0025 } /* code 0025, PERCENT SIGN */
  ,{  14,  17,   1,   4,  16, acGUI_FontArial27_0026 } /* code 0026, AMPERSAND */
  ,{   2,   2,   1,  19,   4, acGUI_FontArial27_002E } /* code 002E, FULL STOP */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0030 } /* code 0030, DIGIT ZERO */
  ,{   6,  17,   3,   4,  13, acGUI_FontArial27_0031 } /* code 0031, DIGIT ONE */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0032 } /* code 0032, DIGIT TWO */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0033 } /* code 0033, DIGIT THREE */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0034 } /* code 0034, DIGIT FOUR */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0035 } /* code 0035, DIGIT FIVE */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0036 } /* code 0036, DIGIT SIX */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0037 } /* code 0037, DIGIT SEVEN */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0038 } /* code 0038, DIGIT EIGHT */
  ,{  11,  17,   1,   4,  13, acGUI_FontArial27_0039 } /* code 0039, DIGIT NINE */
  ,{   2,  17,   2,   4,   6, acGUI_FontArial27_0049 } /* code 0049, LATIN CAPITAL LETTER I */
  ,{  15,  17,   2,   4,  19, acGUI_FontArial27_004D } /* code 004D, LATIN CAPITAL LETTER M */
  ,{  13,  17,   2,   4,  17, acGUI_FontArial27_004E } /* code 004E, LATIN CAPITAL LETTER N */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial27_Prop6 = {
   0x004D /* first character */
  ,0x004E /* last character  */
  ,&GUI_FontArial27_CharInfo[ 15] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial27_Prop5 = {
   0x0049 /* first character */
  ,0x0049 /* last character  */
  ,&GUI_FontArial27_CharInfo[ 14] /* address of first character */
  ,&GUI_FontArial27_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial27_Prop4 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_FontArial27_CharInfo[  4] /* address of first character */
  ,&GUI_FontArial27_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial27_Prop3 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontArial27_CharInfo[  3] /* address of first character */
  ,&GUI_FontArial27_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial27_Prop2 = {
   0x0025 /* first character */
  ,0x0026 /* last character  */
  ,&GUI_FontArial27_CharInfo[  1] /* address of first character */
  ,&GUI_FontArial27_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontArial27_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_FontArial27_CharInfo[  0] /* address of first character */
  ,&GUI_FontArial27_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontArial27 = {
   GUI_FONTTYPE_PROP_AA2_EXT /* type of font    */
  ,27 /* height of font  */
  ,27 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontArial27_Prop1}
  ,21 /* Baseline */
  ,13 /* Height of lowercase characters */
  ,17 /* Height of capital characters */
};

